module.exports = [
  { name: '3d printing', map: '1qepKVwZ5z6HqpoBUr2ipQPbivrJjir3y3UPAGvP#204.9,-213.6,3' },
  { name: 'a-frame virtual reality framework', map: 'CWsQJ418QKxqEztQEYyozPWHiqxEK9JnZBgdSbpz#90.3,-197.3,3' },
  { name: 'abiogenesis', map: 'SLXSGkt642jAz54xrVGEFLVtZmrrB7gzGPohtngF#177.7,-165.3,4' },
  { name: 'acting', map: '5YecPzsqehbb4o4tvaXc6uykmqhzar3AykvRqpE5#47.0,-115.0,3' },
  { name: 'alfred macOS launcher', map: 'tetuczqhA9mYrxXDx4zVWVmEFBgixkRe6SzjsFcq' },
  { name: 'algebra', map: 'AVUfxKqZjL329qksB8jFMpx6zDA2tpQDKGC9v1RW#-23.1,46.9,3' },
  { name: 'algorithms', map: 'M9oKwx4cd9kzJqTpJsoUaqpGo2X2bvfwdp6ekodK#69.9,250.4,1' },
  { name: 'analysis', map: 'mpCNfLpJ5cAtJbUG9twTjqQoaSozpJHzXSyDMr3U#-134.8,66.0,2' },
  { name: 'android', map: '9GNqw9qRvvg1A8Jeo9EW7fm8bcyWWtjKD6i6pa6w#101.8,-23.3,5' },
  { name: 'animals', map: 'uD7brAJerhs2xfCrCjsto7fXj4HzkUBrvQUfEyZ3#121.3,-300.5,4' },
  { name: 'animation', map: 'JzrhswUBxsHBaPtQNHoxPvWApsUEenW4EpeDbsHi#48.1,-56.0,5' },
  { name: 'anthropology', map: 'nu6BzRKfbifbP1pF9SxusxeRK4SqMBD4fPAjbxNi#136.6,-46.0,5' },
  { name: 'anything', map: 'KdeMPbxs8KPixsa5YUq5cphqJnQg81vpHaXcDX2i#-48.5,-680.3,-1' },
  { name: 'architecture', map: 'Q6r66iur4UDMMzdTtbCJgnsYaZbDnAygh8tbBMd3#19.7,-49.6,5' },
  { name: 'art', map: 'LqjxehvfzXszoTjqzLTdcrfwD6c4mSFck9PDgxD8#132.5,-227.9,1' },
  { name: 'artificial intelligence', map: 'wzysPxEVDVNYXebyN8Sp9qAg4mQ56btHbicx99ac#4.0,-85.5,2' },
  { name: 'backend development', map: 'uR5wuu9guh97btPqQaRND2QPu4sxenfzMRNNPsyB#-1165.6,-480.8,3' },
  { name: 'bash shell', map: 'gvKrazbC3joUVUJ6oTpyxHrKtZDsifk28UYyJdq8' },
  { name: 'bezier curves', map: 'xFxmSxUn5zw5FF4ZoNqZsCGjvszFZSEHhy5PuHfE#92.2,-148.6,2' },
  { name: 'biochemistry', map: 'zi4L6xyTss5zyiBkw6RqAqUhzaBZgpXNQk2UNA8D' },
  { name: 'bioinformatics', map: 'syiq5vpE5n7gWTqmvja6v6ivhY7EY1AP61qpz2PE' },
  { name: 'biology', map: 'VbTJQGhPcBZ7kWwXri8sUd1kTSQuAeZH8xkCtTgp' },
  { name: 'brain computer interface', map: 'z8HaiMkaqK9Ri8tJYgKGAv7x2TPiwkRNnKa73ZzC#-41.5,-165.1,2' },
  { name: 'browsers', map: 'YopAYPxSrgy7Pqvs6ztsEgqyHeXrCd5uRQY1zzUs#330.7,23.9,2' },
  { name: 'c programming language', map: 'Cy6YFfoRFvBbgMMWgyN2zaqhj9KPjB23fwxvN2GB#80.6,-9.6,4' },
  { name: 'c++ programming language', map: 'NRbzKJDrEKKWK7pvqSdpBCy2cscxZ1ZMizkxzQik#108.3,42.4,4' },
  { name: 'calculus', map: 'rzNXGzaSkyjn634xxnSb2jwzC7wddoxxxrB91PwA#133.4,24.5,2' },
  { name: 'category theory', map: 'cgWrEEoW3HSA2iysGp2swqphQXSpqVvM5TaismpM' },
  { name: 'chaos theory', map: 'Ay3xy8VuNPMZyDMqzDwVQ9ijtJQBjpm82QWzinA2' },
  { name: 'chemistry', map: 'VdpXxxyVpJm7NedoNqt6YnSAsN7RWyR7mzLh3xs6#-55.2,-100.5,2' },
  { name: 'classical mechanics', map: 'Xs5qLyzR293qpAZLJWY39SuvK2xkW2YxWm61wT2M#41.9,-35.3,2' },
  { name: 'clojure programming language', map: 'q3CqTsNEX43ovcxU9qoYU3wn23Fro7qbWaqxFULX#57.4,-86.1,5' },
  { name: 'cognition', map: 'NXXNu2vC5VfKgx6NGKjryfvrY6xaWBc48cRy6Wtc' },
  { name: 'combinatorics', map: 'MxmPsgBTgB8vwS7wcHpZgvTx5fWrdozgZngVpbrp' },
  { name: 'command line tools', map: 'XcsEDRdzwdo86zsfaQVmFR2pmXCXhkSvyqpynY97' },
  { name: 'competitive programming', map: 'yT4BspbzmdGpQJZz2jzL7JEe3tpVqqX2LZYHoJZV' },
  { name: 'compilers', map: '8zoz2iumK52ZVSsuEr2bqY2cyzpx7icMS1nMsNH1#207.3,-134.3,4' },
  { name: 'computability theory', map: 'SnqXfwJjzbc3Vs5F1tUayBG5RhDxxwTadc3Y6At5' },
  { name: 'computer graphics', map: 'p7RzoL1gYA4Y4tzxrGVtRC5Tc1RLB6UtMnws5ugv#15.6,42.4,2' },
  { name: 'computer hardware', map: 'Lf272jyyVyWWmRPpxs8z4GvsxQqGPLfpZrVhYnMn#-292.5,-354.9,2' },
  { name: 'computer networking', map: 'NMjhSs88CAGYpxwsd4CP8mkzMRj5o42CMtDVJhtN#67.0,-21.6,2' },
  { name: 'computer science', map: 'QKWtVCHyuwbZnuxdtzZhXxs4wp8St7GeiLbKMzQU#640.3,-486.9,0' },
  { name: 'computer vision', map: 'mCmNsBxeiGdRqYefxaq2HXYMKxf8sFWq92qYtMyU#109.8,-150.5,2' },
  { name: 'consciousness', map: 'hSNyGspZ2ZBNebvrRvgmrg62Nk963kgwjAvNAFuq' },
  { name: 'astronomy', map: 'GbDJzhhJy8QG6BRBpQcB4kw98kzM5mmoczhCoPF1' },
  { name: 'creative coding', map: 'FPn7sjCxzFEd6mqaBEwCCexNnwoPyFGzu5ySkMRk' },
  { name: 'cryptocurrency', map: '7TUvLNzE4aUwzNqXurPdcyenQR5sYx9XsJjYcQcZ' },
  { name: 'cryptography', map: 'cHUd9sSPJHjKf81sczwqxPgS7KyJJqzXz1kp3shm#267.1,237.2,3' },
  { name: 'css', map: 'RotqNyXWxoT5pBazqnehMuKLkgHiM32WYqjazgpY#18.3,-44.1,5' },
  { name: 'data structures', map: '2qFq7j3eSx2Szz3PcKGTbsSbM6psoYYGTErdyYXd#39.5,-58.6,2' },
  { name: 'databases', map: 'VsuqhhyBK8PAfvzuHqE1DBmyB9xV8fSePsX92ssB#-23.0,6.1,2' },
  { name: 'deep learning', map: 'wqhKt6rDSZrJR5pVV2TpCv4xnHUsYJf3vZ9SbX7D#-38.9,-533.8,2' },
  { name: 'design languages', map: 'grUmLWNxBRYqRUbRVXqWc8uygE3SLPy7V9tp63nq#67.0,-170.2,2' },
  { name: 'design', map: 'UfyzJtYHJtarpQg5YVXVz7vwYjQvn5FQt4g3pq4C#328.6,127.9,2' },
  { name: 'discrete math', map: 'ha8hqZuHbb5Py7LzxWoCatscK9AZsR93vJbyfqiq#200.8,36.7,2' },
  { name: 'diseases', map: 'qSpAkmpgvtHK27TFhysj9svBh7fBaZKjuFztc1ms#15.6,-200.1,2' },
  { name: 'distributed computing', map: '2ZYrG1D2SizuM5YzrnCNQdNqzZXC1N5nH2aTMbVd#-141.5,-63.6,2' },
  { name: 'drawing', map: 'z4ZojQ2ngJ83LWaew44kstV9f2YX3Huj1pmFUbTc' },
  { name: 'drugs', map: '5HyyfoE5sufZR5RvN9isTCdaYByzxFVhLqpk2MXg#-125.3,-218.9,2' },
  { name: 'economics', map: 'FHh7spgcDGWdg72U6L4u34VRCrW9kLswUHQoXBMs' },
  { name: 'electrical engineering', map: 'QgyDiwvEke8bbXKGFQoh8zC4JUkpEW7THSpjPuDW#1.9,69.1,2' },
  { name: 'electron', map: '1Gr5QZ6ycqVbhVNahBk6qjdSjsttzxuCz3UVDge1#238.2,-68.5,2' },
  { name: 'elixir programming language', map: 'zW4mZpEwWk59LkRXCFQCxLCNGp52Uzt9yHFyk7A3#93.7,-185.3,4' },
  { name: 'elm programming language', map: 'YcsPzMswwUu2QqRzQYytG3ztDyzfEaMdg2oshuki#107.7,-180.1,4' },
  { name: 'emacs text editor', map: 'GQPbqm3QBqQrp8Pzz1kcYFQsDqMppMHkdH84y3bR' },
  { name: 'engineering', map: '6SJjDrFxzofoZjxfpgH5qVryLSYjppJsg28NapzF' },
  { name: 'english language', map: 'oTrSaQmHmUvsfe1y2CpKU4xxnXueJKpKGoyWLZ68#-17.2,13.1,2' },
  { name: 'entrepreneurship', map: '7wRp4x4AGyQt7oxU2PzZpSEGudSns76n1f9WXD6Y' },
  { name: 'environmental science', map: '2qWdikpzGwN6GkfyyevpW85tXxACgjqWGfxyJ7Ph#688.4,-573.6,2' },
  { name: 'ergodic theory', map: 'YpcjTrk8y4e46T7kqFBnTmsEexqtCasGsrbHYTFL#-97.3,-7.0,2' },
  { name: 'erlang programming language', map: 'qNHHXzr4uwFXSHsHsznLkWvXXVskz6hFtjiRKcai#94.6,-255.9,6' },
  { name: 'ethereum', map: 'Qzw4xRpZJLXCBG357zegCse43zFFzkBmssmg78Bo#-23.2,-236.8,6' },
  { name: 'evolution', map: 'vRcTBWAWQsQwUHvqMV9bNZbLDmXGxadnyobphBd9' },
  { name: 'filmmaking', map: 'zwrY9ZyZy5sHmRg8HizhVnJMDpxQnxahdkqA3i3G' },
  { name: 'financial independence', map: 'pEPHR2gDncqZ6UX4JDf24vpFznPpexrrpvouM6he' },
  { name: 'fish shell', map: 'sBKVXzBFc3x9BPDixjauyix3UPnVjYazVBj85axz' },
  { name: 'fitness', map: 'Qruad21hxq43Qw4xHN4gyPZmeKc33cx3BDHq1o47#75.9,-153.7,2' },
  { name: 'front end development', map: 'zRGj6Bjd1T31sVhsJz4HcNbCCz7ZMgKNqJSWSjyt#202.4,-166.2,3' },
  { name: 'full stack web development', map: 'YfXtXRQ4Vys8SZaxwKETATNSWX4rbhHeq6xPxLjm#237.2,-165.4,2' },
  { name: 'functional programming', map: 'yyhkEqtncydaTup1Bfz3Du7juXt5o5Urpp9pnWQv#33.0,-76.8,2' },
  { name: 'game development', map: 'rMqH25BBnT8N9Frhv3L6YCk8NozigyGWgjrgPmjE' },
  { name: 'generative art', map: 'poAjesfjxdw5oHhJJT1LbPi4pabM6gBh1kKzrS3E#296.1,-200.9,2' },
  { name: 'genetics', map: 'YsbzN9qSqh19C8xSu48PVMsDYik1obzQLb4qUNTN' },
  { name: 'geometry', map: 'sCYVzti3VNqepg8uKQxpGQoHnDFy3pyuBiabecPn#-28.0,104.5,2' },
  { name: 'git version control', map: 'dzhbs3FRB4z143969SjnPEDspe1Gp3SEppissAqy#77.6,145.6,2' },
  { name: 'version control', map: 'uniqtY8eDpC7Kbt5kRvu1V3iY2AQTobYS2WsHnxP#-153.6,-180.6,2' },
  { name: 'go programming language', map: 'qpLq1TfqPWmu9sszrCxEM4QsWUH547TLNQkyfTyQ#42.8,-147.0,1' },
  { name: 'godot game engine', map: '9J1fJTLMtBohP398Zs1axCyQf7v4nFyoMTWuG9P5#40.6,-188.4,2' },
  { name: 'graph theory', map: 'dXTCUUkXaSp99j3nbD2Gzxn5NMBn8dyuU4atT51n' },
  { name: 'graphic design', map: '3LqqYjEYQWQsrSk3Ypvy193fTspqZuiCy4emM7Bz#16.1,-36.0,2' },
  { name: 'group theory', map: 'CBJmkdWELRW4PYpUDj5ypLeydiAn1io41CrpHpF2' },
  { name: 'haskell programming language', map: '2t2hzaNKKxQ5L6zaAEgpguLbJYL24gX8hi8hgrFM#80.1,-175.0,2' },
  { name: 'health', map: '4LknBLWzBESbxERfpYQZsa2Fv1k3Lne1FjVsD4ys#-32.7,-31.4,2' },
  { name: 'history', map: 'viRDhbpcrjLW2MSyzGJyhzgSqryics23wcLfJTxR#1644.7,-1422.5,3' },
  { name: 'html', map: '9XKbbxW8Ft3fzP43bPwtqU3PRhDzp3VjKsqLntQJ#-74.4,-31.4,5' },
  { name: 'http', map: 't1dtQBegP9uwBMKgxszHeHhYRT8EzDvbxy9Zbstw#-12.0,-39.3,2' },
  { name: 'idris programming language', map: 'FALM4KzKneJrqTQpd9fc8ZQyneE228tWpAVcB5f1#148.6,-238.7,6' },
  { name: 'industrial design', map: 'sG3PrxZ5rtpFSBEWewrbfGkSiaXduHMZxEWRRewi#-26.5,-174.8,2' },
  { name: 'infrastructure', map: 'VBPfyy3FxxfSpCB6xzjQUxbKbmvPf6w9W7snssVb#63.4,-373.0,5' },
  { name: 'internet of things', map: 'paZEegpBdjystmyVhqfqX7PoPquz1AEWY4JvQkSk#-11.7,-285.8,2' },
  { name: 'investing', map: 'GLyTce5yc3y6fxsHJqZSoP3UnR5pSx2My8cudp7o' },
  { name: 'iOS', map: 'm32Zo1SzPiqfWqJvpUwBMuTMCNVXejfyWfZyeSFz#26.8,-39.9,2' },
  { name: 'IPFS', map: 'Hsex87wcsZbzbwMNzbaJFsBPFJycLymJqA7sotvg#64.1,7.3,2' },
  { name: 'java programming language', map: 'XcFAZAvk82ipqdis1UW5wznzxBxuVbx5iHLwgLHP' },
  { name: 'javascript libraries', map: '5PazdXmKxEq1mDpksAfWUZFdJTpvAHpti6Cir1S2#315.6,-109.4,1' },
  { name: 'javascript programming language', map: 'QQzCynmUtZpAuyGipqxsvRJ6NPn477o9cSjCGqqR#-98.1,-328.5,2' },
  { name: 'jQuery', map: 'Gr8yvuKJCWgjaeJXoiUudYqoid8oeky6b81Cwunf#34.9,-47.4,2' },
  { name: 'julia programming language', map: 'o5MkZSpM5SvDhrBTz7mvrm7qLFSFXXAgV5xzKWQx#93.7,-129.5,4' },
  { name: 'keras library', map: 'rApczcRbzmMrgkZtP6QmEyTRGUvgiyThASZrPP5C#-17.0,60.1,2' },
  { name: 'kotlin programming language', map: '5LipbLiRfryhTsqRL6za1x5qzpQBh3mmD997Kwvb#-23.7,24.8,6' },
  { name: 'lambda calculus', map: 'P1fXveGBaQQQF9u1ZjGzqJzT9vnUppxPgyrnYFzM' },
  { name: 'languages', map: 'stsEoNGkUKFSyU9tsZ79xwDwQqQWSufCXafvSdPx#-25.6,-188.6,2' },
  { name: 'LaTeX', map: '4bwpnfgzEsxWdzsbgDzUJdK8qxmvEKEK8tdWPmD5' },
  { name: 'law', map: 'xGXnpQKEqRv7eHeqTwgz8CsdknxhnWZj68baiyCd#-53.5,-176.4,4' },
  { name: 'learning', map: '7yPviE4oYJJ5xRmDYrTQfqWCkydzPoRXQAQ3nyAJ' },
  { name: 'linear algebra', map: '9GQnwWMBYXMe1XjUD8G21qpxiyz5B4MraPtL8xyy#102.2,46.0,2' },
  { name: 'linguistics', map: 'RzvJjKnkfVYcSZxfU8vozrx94yqAemYs6s5SRnoz#-63.0,-92.4,2' },
  { name: 'linux distributions', map: 'uZFAizZuJGxuAr4s2XYQ3vCLsUELCqLzL8XpzmxY' },
  { name: 'linux', map: '7N2X8wXv19NAjB3gdrFkfzqqT6LpDyzLAJVfx15e' },
  { name: 'lisp programming language', map: 'U8N8tR2D1Ek1SUaLoNEDwcmoeeBRMkEUnd1XxfH6#53.4,-58.2,3' },
  { name: 'logic', map: '1GGWUw7yg9oqPVsqx83FwnMa41ecAcYXYJp5GRRR#46.1,4.7,2' },
  { name: 'LOVE game engine', map: 'gKQdRD1VLLAi1etGdsKnhtXsW4WX8y6HQUQBx6eN#-51.5,21.4,2' },
  { name: 'machine learning libraries', map: 'PVcz8iqUfa941KTpBqXgpiP7Asst1yGcqVa8Kmit#-183.6,-218.9,2' },
  { name: 'machine learning', map: 'k954FWFNztnkphWmNqqHz2dqQW41LeP1SLqkqqjs#316.4,-944.7,0' },
  { name: 'macOS', map: 'YxEVejLH86YkpNGB5AWNcXUaasejqPngAg8wgiQt' },
  { name: 'macroeconomics', map: '7yruRs7n4ySrpYqFppAaRJrdcf8MKpAfpyjnqV1z' },
  { name: 'management', map: 'YstbvV9fn1zzpkXxCsSAnzheSysDKn5Q3B8koMuf#67.3,-166.3,3' },
  { name: 'marketing', map: 'Wm2fSqKWEJyyZ3LYZsgy2x6Yb8te49t968qqypUs#79.7,-75.0,5' },
  { name: 'mathematics', map: 'JD2DJUeZSAwQzyb5KceAZ6bfuYaLGqsDkpfZg1R2#461.4,-683.1,-1' },
  { name: 'matlab programming language', map: '5Sx8gmcsXTxznCp11pAggrxCzWkA4VLLNFx2RNEH' },
  { name: 'medical specialties', map: 'zv6SgpSpxyG8ZzXs7TpqV3Lzzms5yqa3pzC9CTnn#-33.8,375.8,2' },
  { name: 'medicine', map: 'CbZkPeEWbQxNRtoCAzdy3Wx1Bz3BLzC3PsK9yF5q#-65.3,-72.7,4' },
  { name: 'microeconomics', map: '4vwsEGr7GgX2F6iTU1gzu4wCByWxGi9HCTqW7ABp#12.0,18.5,2' },
  { name: 'mindfulness', map: 'X1xhDwGWzsx5JAYpitKYQmX9YtMgR3CBpujMkhj8' },
  { name: 'music', map: 's7pJzgtWzzkz8ubfSzWxWyvuReC7eLVSHZqc4aRV#-45.4,131.1,2' },
  { name: 'natural language processing', map: 'nFFywmhppMRxw1Z6n7QNxikisQo9q9egH5jL8PfD' },
  { name: 'networking protocols', map: '6fjPX63yK7dpB6Vs2uxjzqvZ8xBw2ymoDuq48wPC#144.0,-374.5,2' },
  { name: 'neural networks', map: 'VznvpXy4JfeyVL4toshCQE3pdyHvLzx1bTGUpze2#210.2,163.7,2' },
  { name: 'neuroscience', map: 'qn6XqfNxftWrVm4n2Xs5BsPJok4KEFTJGpNixELq#-75.7,-37.9,2' },
  { name: 'nim programming language', map: 'h8VJGBSS26e4bB4WdUx3myyoUczihJtvzGGj8whg#92.9,-58.9,2' },
  { name: 'node.js', map: '66sFsUMNvxTztuXk4hHSKRByUXqnASaLTXMNrNkv#-68.4,-126.8,4' },
  { name: 'noSQL databases', map: 'mLEApxUMnfyeMpB7WzzkUdUNAweVk9WWJZpXgsh6#122.0,-190.0,2' },
  { name: 'nuclear physics', map: 'HbfUFjzkF9Dc1GnzXqs2rUpVy9dEsWBL61wKvsx7#98.4,-101.0,2' },
  { name: 'nuclear power', map: 'VsJNqTHszge5FaDgKQXk94U6mzvFT5dSHd5cRu1p#1.6,-40.9,2' },
  { name: 'number theory', map: 'XtFzGZzt2WmZXRs6R2yecX5yqPXn2rGvdTXhbtJ9' },
  { name: 'nutrition', map: 'zUyb7rGF3UvomE9YgA4tJ8vhfrGxZ9dvPNy2EL1r#158.0,38.8,2' },
  { name: 'objective c programming language', map: 'zpRZZGyaquCMMatMhbHqoyNDum3Nh6VTgyRwyDuY#41.4,-113.3,5' },
  { name: 'openGL', map: 'zPHWFpAprmq1Tt3YGm3ZBE1pysmVUYSgDhsfMVfZ#47.2,-43.8,2' },
  { name: 'operating systems', map: 'KAxvkPhxHhf6v2xxJ58HXhduppxpTz8xznmcuvBZ#111.5,31.0,1' },
  { name: 'organic chemistry', map: 'dhjpxEvxsiojxW3zpYLauuaPtunmybtWNfUjmy4b#-28.4,-94.5,2' },
  { name: 'penetration testing', map: '4ihKdHT7ZKc1a6hp7MiFFYGpzA4Dm6Qu6sr5LdMT#62.2,-46.4,2' },
  { name: 'perl programming language', map: '4XCVExihWLgHvFxnJZyxLMYWWt8rfsgi4Hrqykya#20.0,-61.4,2' },
  { name: 'philosophy of mind', map: 'UMM4zxspXCaoU2PXsuxQdj8ERppHZEpkv9oQAiuB' },
  { name: 'philosophy', map: 'DaLRfu3ipMHEkhxuzqKTgbZPLmVGTmN7khBS3xqZ#-28.4,-144.3,2' },
  { name: 'photography', map: 'ARzVgj42iJRgaDwqcHqpy6bVBskmZxbbzGsUyaYn#48.2,-139.6,2' },
  { name: 'physics', map: 'RfCpjqozA6Aq3j38RvzUnZrhFGMnpCsbRrpAsUWj#-201.2,-115.3,1' },
  { name: 'postgreSQL', map: 'QrSn9FP4n8QBgYq7VyyJdRzwmZdJq6tpKqsjvsi7' },
  { name: 'privacy', map: 'uFiw9mUYxyQjTnTcHqpX8VGsH5sSVSWztpY5AyWJ#-154.8,-53.0,2' },
  { name: 'processing programming language', map: 'zR23tD5fCFaQox7mHfYkLUgiQCDvMcz8Ragd98QR#128.8,-311.3,5' },
  { name: 'programming interviews', map: 'XSoat9hfA9vpEu9LsEStbuAzNWhPHZqDyh24sRzv#583.2,-55.2,1' },
  { name: 'programming language design', map: 'DGpMF54UqFrrurzbs77HTzyq8HswHBEwq8xdg8hB#312.6,-178.5,6' },
  { name: 'programming language theory', map: '6GZfjhTKw6cscXsr3MqFCLAfPnCs9dEEWSAuptrR#33.6,-596.3,2' },
  { name: 'programming languages', map: 'deC8Q7qpC5GxM41ysqHhMHzN832JMUAL1Fc351Td#-95.6,-555.3,1' },
  { name: 'programming mastery', map: 'RHEKsTCqdDLjzVaZ8DzEXkeEezxpmyLsqf5BV1Mt#112.5,-43.4,4' },
  { name: 'programming paradigms', map: 'WoxCvQtJKD7iFsABg3sRjfAfQ2g5ZQjmTt6Vd25i#272.8,17.1,2' },
  { name: 'programming', map: 'XK73eU8WNHy5qHEnsKTKqSdsVkXzs2iMtvTmgYpc#354.6,-28.1,-1' },
  { name: 'psychology', map: 'cmk4fh551FmyBm5Eg3vAbj9zruxk3W41XNreG4vy' },
  { name: 'public speaking', map: 'FfGBsH3yoyhMqibLaNW8hf3ZKGe59Yx7yiNDBxc3' },
  { name: 'python programming language', map: 'cmzq9sEGAyyNyeZrNA7UyQa8JpsqHf9QzStwFqGT#35.2,-11.5,3' },
  { name: 'pytorch library', map: '9ABQqxkZGqGtY2QKRkwyt7q3pfzMkoSQTgJ5anZn' },
  { name: 'quantum computing', map: 'F8ubCrxApr7pFiW8TxvNyyzD51WqHkzVDFMN4cyp' },
  { name: 'quantum mechanics', map: 'qJ23VQZs8r5YToae7Ch6Tein6h7U5yhAiw8enxsH#66.7,112.9,2' },
  { name: 'r programming language', map: 'mUPs3DfcabhJX4AWRPWVdbYRkqqad3ZL2SjVFoPL#66.3,31.3,2' },
  { name: 'rationality', map: '9zjMKNDyM42txQ7EWiEafZGWGMzdrkRtd1sybg8c' },
  { name: 'ray tracing', map: 'xXFt6yDav79DvBBUnPbsqtVzQH1fXBqZGRaYRk9D' },
  { name: 'react native', map: 'MiLsnxiprq4jpBMTBiHT48Kt1sZqfF23hEuyGLKE#145.5,-106.0,3' },
  { name: 'react library', map: 'ifaZsjVmDsFxTdqDDix8s3GyXibGvCArpc86ViZM#9.0,-252.8,2' },
  { name: 'redis', map: 'Fb7dmtCvahWRF1LWybq5JqtPjHwBeF4mxoV7zLB5' },
  { name: 'regular expressions', map: 'reBzaM1mn6WWuTM5iRAtrC1o7LzWBNwspT9pxNT3#86.0,-125.5,4' },
  { name: 'reinforcement learning', map: 'eKswyDv4KNY9fePuF3DcWvYZjtTaBzxk581Mw7Ru' },
  { name: 'relational databases', map: 'y48JgLrYtbyNrsKyRze4WHzhYVrGZks9N9pvsekp#-44.6,-268.4,2' },
  { name: 'reverse engineering', map: 'dtFqPNRpHxvWsy1ySv4oA48sDxPa87SpfFq5Zzqz#85.9,-1.1,4' },
  { name: 'robotics', map: 'wh2SoPR7RC3QvWxkk8Gw3S4Ev8AsqCrnozKk8Hv2' },
  { name: 'ruby programming language', map: 'tjqqGCFLZbqp4sEDZqv7H6DB5Xwx7FUjhDdpBnit#392.6,-414.5,2' },
  { name: 'russian language', map: '4eQcjH3g5sypLz42tryUQ49NZzfhE3Crb4m9tq1v' },
  { name: 'rust programming language', map: '7Q14XaYLnco9X1oqfouxpibjMz3Asy6PVDjf8C3Y#52.4,-114.2,2' },
  { name: 'scala programming language', map: 'z5jpzSuE3Tdyy4TFpxz3vbZMAKyS6B4cDPNQKmS2#78.3,-188.3,5' },
  { name: 'search engines', map: '7YbqKxSpWxkBT4s4p8N5HghpCy6n8XNHwSHAppzn#49.8,139.8,2' },
  { name: 'security', map: '38DGvay2sqnzEMAZ4GnPNKzVxDic1gStaQq6dn46' },
  { name: 'sentiment analysis', map: 'BTNhqptfyxynrT4NFoaLAysgHnkKgpC98YGuKqRA#144.1,-175.9,2' },
  { name: 'set theory', map: 'nczskizQHzyMnnpAxxg5D2hWuMshy2AF13pkGNdk' },
  { name: 'singing', map: 'LzEyZ1zXzYtx17vmqsn1ddeVAzRNPZscLvdgNkmc' },
  { name: 'smalltalk programming language', map: 'rv35EzC72HtQBmAse2k9WgxyssY4qTbs2u3FU9ux#85.2,-136.9,5' },
  { name: 'sociology', map: 'syqmsqY4ZxxGLHMJFc1s84WXdU4eC3MxdZPa9eSd#92.3,-91.2,5' },
  { name: 'software architecture', map: 'eGwQJjrztCQoaUZwUdAeq2o4C1s9mdHKRKjX6iRD' },
  { name: 'software defined networking', map: '7zQmJgzwiJusj356NbqrERGDJkX3bRSLJH65tp35#86.5,-354.3,2' },
  { name: 'special relativity', map: 'gLpu3axPp2y3uXJoq4G5F2bCzbLNDn9Vi1rnaZLH#10.3,-241.0,2' },
  { name: 'ssh', map: '4TdQ9XwhpRja4c9Nz7XvCSL1k3UsHFs8U2fxjfwd#51.1,-214.1,2' },
  { name: 'statistics', map: '7cSLjj5rauAnjWT1zHqEmqGkixvoVWaMz8C7Q2aW#79.3,186.4,1' },
  { name: 'sublime text editor', map: 'ndgjqFv81GzHxJR19VmpzcZHdE9yM6yFDNoiqZZu' },
  { name: 'swift programming language', map: 'vAJcWyzzTubpywgp8o367gPWvRUxi2y5r2sZMryb#138.9,-214.6,2' },
  { name: 'tcp/ip', map: 'zZbLxuhSrDnUaU3aP21wpUwt62zmVpkct13QhJjU' },
  { name: 'tensorflow library', map: 'qA5158JZkdJzGWzr54AswZkmxPnwBJVTc89mytzy#15.3,278.5,2' },
  { name: 'text editors', map: 'sy7bTZuzRx2DGTnB4zrxS8xH3bexEiednueetUm4' },
  { name: 'theory of computation', map: 'nv2bgFsqXvmrTByTt5W1Q7GtXqu8skYRTyac1pDU' },
  { name: 'software', map: 'Y9HmMRYdZycykNjqHMtyQ2G7aSVJXbRFcsxT7prQ' },
  { name: 'torch library', map: 'zqcBKdtGqSVwEik7gqrYrynGeyfSXYLVyqxE72Q2#25.9,-194.1,2' },
  { name: 'type theory', map: 'eytyqpDLBmrC4xVnHCDqRVBZi39xhXBWnBRSTVoM' },
  { name: 'typescript programming language', map: 'aWy8dg8k9N99SQBvu6zMeAjyfHMrJswpvD5BiAXr' },
  { name: 'typography', map: 'Dpe6usjyhYStxvMwwrGB2oste4DsnbGdQxL8h1eU#-111.2,-63.2,2' },
  { name: 'unity game engine', map: 'e6eGCsYMysgfLWp32sC94KKjriUy5UNmBJXJGoox#66.3,-295.1,2' },
  { name: 'unix shells', map: 'YoH1p2rK7xGoRohmsZ3CZKFrB6QhqQh2gLq4bjpz' },
  { name: 'user experience', map: 'HxHcbJzNjqT4s8esfDyUQYEACFDysxTx43FUGdYx#66.3,-50.1,2' },
  { name: 'user interfaces', map: 'HxHcbJzNjqT4s8esfDyUQYEACFDysxTx43FUGdYx#66.3,-50.1,2' },
  { name: 'vim text editor', map: 'onsumXxs7xywXeQxDHEJxfM8pQ5YNxmfzfxQc74T' },
  { name: 'virtual reality', map: 'mKhEXHiMUXpGgfJxDkqbgyxN3MRp3bwug96a9zo2' },
  { name: 'vs code text editor', map: 'ZkkpJ1Q28hj2Lx4xoU2eWqHWojC4RDjCsYYUTQPK' },
  { name: 'vue.js', map: 'nGBJtTf4DYUj4sxXXZRBn7YkRnxb1LtqLmzhonLn#-70.1,-28.1,2' },
  { name: 'web crawlers', map: 'tfSGpEVZd5EqPFzEzetA532qCfhgUDfbVp6gU7zv#46.6,43.0,5' },
  { name: 'web design', map: '3irQvGhTDXsWX7yHqzQkR9JWhq9kyaJZ4otN7qiR' },
  { name: 'web development', map: '85uh2iN4GPhBJpuyyuWks5a6niyypQA5TPBCGnAN#521.7,-260.4,2' },
  { name: 'web performance', map: 'TTiDHqPUigF91yBHAFSgbhNckeUAGZhNtxiavEPB#-4.2,51.4,2' },
  { name: 'webpack', map: 's6pamFzVLsjqEmECkedvcFuH8pdM47NuojDs8epy#98.0,-153.3,2' },
  { name: 'WebRTC', map: 'Z23exvKV95hC8L5i5kcyenuTr1XykRqXWweZAqfi#52.5,-6.1,2' },
  { name: 'WebSockets', map: 'MCHX7afgsj6V5qXGDEpoqs4uJhG9yDPsTaz4WyP4#108.9,-326.6,2' },
  { name: 'windows', map: 'yxcnFoyVpJecxFRoqfQ8orzsu3zesCAcS9jjMPZM#42.3,-43.5,2' },
  { name: 'writing', map: 'syW5tDqyLdEPRQYt2d8bhbt79hqPxreaaKo3BqMG' },
  { name: 'quantum field theory', map: 'gDAemvFSLEMi7g9ozVTKp7yW2onyv76X5cspxeVQ' },
  { name: 'guitar', map: 'xPUGxGodprtehL3P5zd7dyzmTeaDYiCQxkVp8nrF' },
  { name: 'model theory', map: 'M66CXTQkXDysSKDp3a3Mq3Dbwzy5x398Ayvzc1Ey#214.1,37.5,2' },
  { name: 'topology', map: '9Vyqzw7KposgvsspFnRr96nFCyNcKKUVG4hpuNYw#-127.9,214.7,2' },
  { name: 'knot theory', map: 'Gq7pA3rtpYhZP2K1MhMFwmy3YaEpvdG13M5wjRBi' },
  { name: 'php programming language', map: 'PRPMKGkoCxUbGwDxRxfWCPspQppWEL4wcrf3LteY' },
  { name: 'meteor library', map: 'HbPdBs4yqvN1FdoScE3PVNZwnXcqdddWqXkGqssc' },
  { name: 'scikit-learn library', map: '35hVLCpp3wbpsx4YqVD9XxpczbpPpyWJjwWfsfAq#-12.7,18.5,2' },
  { name: 'redux', map: 'eD7tx71JUqC6R4iqaPGxzvdR2ocpqGq5TVsxp2yk' },
  { name: 'django library', map: 'K5WJhHspfaaezNNbNRZYxWGEoofFqnQVTa3ZcxEz#14.7,311.9,2' },
  { name: 'german language', map: 'pT3imu8pRh4xtPpe45UYAEGz7ehkMqWna1sPgWbL' },
  { name: 'chinese language', map: 'amC8qjhodpnZHjXHDxxyeSpKSMU65DUb1yyirRMk' },
  { name: 'query languages', map: '26VQE2ahqWLR5jRQCdsChym1EUP2Ls8AmQ64aj2y' },
  { name: 'graphQL', map: 'QBvN8M3BBDqL2TKXpGzyycUxTMYcRzXpQoJKDcdq' },
  { name: 'photoshop', map: 'Bq15VPP9eVsmunFsM9RAFjpawSsgpuCBSi9ou3ye' },
  { name: 'docker', map: 'mckfV3fnWaJJirpCTcieUhRdyMT3TuLHq6RY54Gs' },
  { name: 'kubernetes', map: 'qD6Dva6VnUKLM1xg3tisnTznnXkBgpYd8nfyjGkn' },
  { name: 'aws', map: 'TCxkEPQuB1ApGPDJT4RcsusD7JFkgNq4HjwAqbLj' },
  { name: 'c# programming language', map: 'NM3CPb7URmFnPyUxpyybKyCSgiY7sZP8iwBxwvfj' },
  { name: 'blockchain', map: 'Cqy6H5RRvkwBTFEsTFH1eW8zQFA5Gzvoq6ssjFxc#447.8,99.7,2' },
  { name: 'data science', map: 'zxRG1oYfCw5DU8ExnRnyJt6qAWz9MM41sqhniGyv#-9.1,-47.0,2' },
  { name: 'apache spark', map: 'odBHYpJQbM7LnyCw69K3KHCrKBBzeAUUQXktaKdf' },
  { name: 'software design patterns', map: 'yyJxSXTCh9xqmnCSbfoD5Ms7Nry1jxcymUDfMNqB' },
  { name: 'japanese language', map: 'F7y3iSAwZdzGnRRWLur3RpXiJviy1YF7QxZwDLxv' },
  { name: 'd3.js library', map: 'oABafsSirqHz4o8Nh4pLqwCjbqnkFE4YturNm3CS' },
  { name: 'graph databases', map: 'kAMXBibSaps4PdfxkB4jBoYBxWBfMbk1eYEzo6Cz' },
  { name: 'angularJS framework', map: 'QYBozsiUWZjbqguqyKSUV3psfhganW7PB1Wapxax' },
  { name: 'webGL', map: 'pRs2UppBdxxyS7YxD3KuqyMsFz5BNsNAyyAzzTfq' },
  { name: 'software development', map: 'C6qyyeVEzfVCyvpxD7digZzzGxV8hvcwdzAkkpjF' },
  { name: 'DevOps', map: '4pT3AeEEywqSgdxTFBRgq3bmFpLs6s9YSaNMrxZY#128.0,-254.9,1' },
  { name: 'laravel web framework', map: 'MbpPqGzHzySQesda9G5umY28S3spWRbzgCrGb4Uv' },
  { name: 'computers', map: 'pB9HWsxJd9fybGJtXLbiXnrMdzPhtF47yKTq3QMF#15.5,242.3,2' },
  { name: 'arduino', map: 'KRHuHfpmq5DzmpfFEgyvSyzQtk9t6oy7faNKbtiL' },
  { name: 'raspberry pi', map: 'TWYxfqzhfcp2sZJUGpHnZqz4fY8YFAjiuv6JBhDQ' },
  { name: 'convolutional neural networks', map: '88ngrfYXYvJvtjsrUk6yEB1wwkKHexABji2z6sjn' },
  { name: 'bootstrap library', map: 'gkqG8tMFYa6K3qpgvqpgnz85TsJ3UpwCuiQpQPjK' },
  { name: 'spanish language', map: 'xb6QwzqtZ2sZ2ryvTeXhA8PnUdzFTWZocEoCxeZp' },
  { name: 'french language', map: '44Pdg9ZnUsddwk5iWYwH2q2a5xHspBesoDQ2HY31' },
  { name: 'dancing', map: 'Tdvsb72Fqon42xkZGHsQx1xfKk6F6eGsgPAjCFpq' },
  { name: 'software testing', map: 'ELcJKvcycS3o6xNu8a6pgF88wCyq5wUkZRWvsfnu' },
  { name: 'everything', map: 'KdeMPbxs8KPixsa5YUq5cphqJnQg81vpHaXcDX2i#-48.5,-680.3,-1' },
  { name: 'assembly programming', map: 'hKbd75qAYjBQtWMN4pzVcVnujGPppqWUKvFyYA2B' },
  { name: 'WebAssembly', map: 'hGPfuwm3pbzHXVVmB3kGRJKcPGPgeZAVFQGztxHW' },
  { name: 'open source development', map: 'i2KJsa46DzxEMaziscL7xMzJMxqAtnNFNAXaJ6d1' },
  { name: 'information retrieval', map: '3WHuPMbUhikHhUQyKxZZ1yapNe4yp9jQcz4u55my' },
  { name: '.NET framework', map: 'dPkMCq9p7GX5ieAbDGYLsrkmCcz7rhzvpYp7HdPx' },
  { name: 'nginx server', map: 'vgUdobqCgPAzpNFwxi779aqRiqcHTXcgmrskyQqd' },
  { name: 'ruby on rails', map: 'Cyv3UUXjxZst5FjBnpkSdqn7XtqWmiZsJL3Hqqec#5.0,85.9,2' },
  { name: 'ansible automation', map: 'qxB5SQXpxFML8WSYfgpgs9c1zvyyu1JXGbGzSZGf' },
  { name: 'babel library', map: '8MxSwVTHS8KP3pptyt26TxDj2urxLsTxoaquJGiE' },
  { name: 'games', map: 'xoSN9tB2yvSa2q9kboV32BC789FasA1HNxMfy536' },
  { name: 'chess', map: '2PqeoMbRrznbwyf6AZjpp9LszS9eHCfyvSGDQJmf' },
  { name: 'go game', map: 'ymzxX988M4yJD9FpCKBQbBYwKZDay3yyWvixuNqU' },
  { name: 'test driven development', map: 'pehL4xybBLbCbwWMjtREazVNSXVhSfxKYAe9EYAd' },
  { name: 'mongoDB', map: 'q2xktwYoqXPzUGxvqg6QQqk5MyATv8oy8nkCEsrh' },
  { name: 'unreal game engine', map: 'yRZNc3qGqiHGa4j1PQFP2MbwukvassARw1xfWyXx' },
  { name: 'blender 3d graphics', map: 'zr3hcyysGypEUsWfPBqat9kSpTpkQzjb6NG7K5EL' },
  { name: '3d modelling', map: 'KwqKLxpHNEMg45pZ6PpMQmgWimEdYxWa7JzTeGTi' },
  { name: 'piano', map: 'pvMP2qSLMX41bu73x5sazays2sYQXnMqkWz3wSEc' },
  { name: 'lua programming language', map: 'shBhz6QyUcsxTG4D63sou6E6ydvR4A4dX6KvJ2D4' },
  { name: 'dart programming language', map: 'ZC6FptzepkYtF6P6fcyGTdKLkGRPrUvcJZFNpGTK' },
  { name: 'OCaml programming language', map: 'xnifgKpgF18BD4GzLJY4zKfLKeV7rBXRVGqnVrL3' },
  { name: 'linux containers', map: 'X2kj5Djhxkmr323zDauwMThaVUQHCKMtVtaauKu1' },
  { name: 'java virtual machine', map: 'XyNZszb6ME9zL5EwesBPTCypXWAJjKfu8g3FxtfQ' },
  { name: 'virtual machines', map: 'Y9qqxCqNzSV8GqxCg9yJvJGsvTJUSb3a9DzvvJGJ' },
  { name: 'Neo4j database', map: 'bx426tJLzof9vjdkMH2zxKAZXABLsWd2CXHaaVV3' },
  { name: 'bots', map: 'cEiDW9MbfjEwzmmE637yBJE7WgHSNtx7zSMsTmVv' },
  { name: 'software tooling', map: '6B77dXUMkyNUm2KxBT6qypwqcXz23vXvkqz9Ezdr' },
  { name: 'productivity software', map: 'M6LrzfnwSvKBWGhNgJhzwnc7mkKPTq17VqPBAqb2' },
  { name: 'karabiner macOS app', map: 'hqzoDQSdDSLHK8yssrbbiC6SdhapeRg9SGNeznPk' },
  { name: 'hammerspoon macOS automation', map: 'gTuyPVTtpQyUuH7HZhd1jeBpio2q7p2zFxLN2Zzy' },
  { name: 'markov chains', map: '1NpiefgrirDdunaD1stiWpyX3bcQbGMKP79hosmN' },
  { name: 'probabiliy theory', map: 'qnagoHf2YScqPiVBsPpgcB8Dxmdm9ku1TN9eQhTd' },
  { name: 'LLVM compiler infrastructure', map: 'sQuPeeiDsBpGJDCz4mFg25iP2zBzo2GxhzjkCTBJ' },
  { name: 'computation', map: 'QWix8KpcBYXDpa7zVmVyiRbdv5KmAszxZqfyCP7s' },
  { name: 'computational complexity theory', map: 'HhbXPapV6af2Kb8dB5xDLJoLahCpKsuCWzucVrk7' },
  { name: 'concurrency', map: 'mb8GSLMzQTjoqN1AnmMbE8Uv91pyKfbA7NdAvvyk' },
  { name: 'control systems', map: 'r17byHmpCEnHyTYCity7LXPGxD94d1aybnv1xzVW' },
  { name: 'spirituality', map: 'SmSpRm4TvWTpqxxXLPtyyqDhytKfLG9oxRrW8ujj' },
  { name: 'buddhism', map: 'd3Fxm8vfSbYWpbZtmwWjxxwPUfxEsPs45iPGydYp' },
  { name: 'watchOS', map: 'JVr5HFsfah63syE1PsYsczMxc1ZhVQVZcQNxonDa' },
  { name: 'tvOS', map: 'eqCzKZyfzu1zsoiGnVqehJbXDqRo3HYm6Ww1Ssdq' },
  { name: 'virtual private networks', map: 'CzViS3qsYSPreTTjveyGSmfFJQ4Vy9GJMjJdXn5x' },
  { name: 'hacking', map: '7dWQHvRBshf6cmgczxFGLTq9Lqg5DpiYqxs8UG3K' },
  { name: 'information security', map: 'JnJxmfMwcigFArLsxvGTi1VwpK42vxbZzfBDSaEr' },
  { name: 'ethics', map: 'mAqtpK7sLQd15ytMqPAL8qvfqbRKgAmsyxkyWtnc' },
  { name: 'startups', map: '3qMybqBsd4E8yeiP48HYyT6s6aSGx17EMaKffkyk' },
  { name: 'vulkan graphics api', map: 'ej8XKCb4Gopu2Uxz5Cc6qRJyraETKeGXdABzYNYr' },
  { name: 'metal graphics API', map: 'ssCTRUmvnugyPUfquW6ihpnyZdwKVySz4gpXSHoY' },
  { name: 'scalable vector graphics', map: '8pnx8PXUk23xQbo8W3vBEKVsqqzgnAQrbFpyCgu1' },
  { name: 'vector graphics', map: 'o9uU98MTo7erfjPjsz7iuktX8CHBW77aZZ297CpG' },
  { name: 'character encoding', map: 'P1er9W1opUoRpZx5dhz9XtSr9Ff8Cx6ksgZLs6h8' },
  { name: 'game consoles', map: 'NN7AnVMbqvozzjkJaZVUsSUz867pNyt6hAKsxa2w' },
  { name: 'sonic pi', map: 'fah1U7bBiNFbxtVCwPT9MpCT4mbovqxvqTkUqpn5' },
  { name: 'atom text editor', map: 'sjyyVYFviACirWkDBZuW2CbvwyGbaAAy8aYYnoc2' },
  { name: 'earth science', map: '9rmJaLMzJ4Wq59fVfrzF5jA7u3ZFVbUvP1fYNyq3' },
  { name: 'geology', map: '43YS6dpa4VgsF9KSdvwSsQPWw2SFqWUDidZ9Xnmi' },
  { name: 'space science', map: 'rq6MV88ZqvbczWGvz7o7EeXDWaXZvBBvhKxjopwW' },
  { name: 'recurrent neural networks', map: 's6VnQhjrxqFwmXDqvnpZa3sKuornySRcqgJwLSeJ' },
  { name: 'ketogenic diet', map: 'AoAE4txQminSymyAA5UB4zEPunffJgD5feWVBJeH' },
  { name: 'general relativity', map: 'Jx67uwFCxmdrGPDEYEvNTzW1GybQ63qapyojnzby' },
  { name: 'spacetime', map: '1LpvWjB8Asdugy9agESKtmwPwqnd1Sb5zzrp5hQq' },
  { name: 'black holes', map: 'Hqcng3n3skirTjVqtR7qbRLrayxzGXTdwCqJ2sBw' },
  { name: 'galaxies', map: 'iMsiQqxH5FB5jboayXw1qxAh4DsyooU8js3k1s8F' },
  { name: 'universe', map: 'bvabTANvmfGEqv6e7GwxVtqa5SPy5anapYcyceYi' },
  { name: 'world history', map: 'sht4GTMSXhqqMcJaCU3RD8Z6uSCZRa6Jn66BuWdD' },
  { name: 'historical inventions', map: 'nY191VoPpqju38NNNArs2H6spAQqQWVM7ZxXxBhz' },
  { name: 'JSON', map: 'm1UpSRGpVqQAodsPqUCJHiffqG2PmBNQ8RJ9wx3L' },
  { name: 'data serialisation', map: 'wqJZUS4hRZx9ApSm3gutDz86Po9XDtCMiydKwCJP' },
  { name: 'protocol buffers', map: 'Foo9ss3x4RvFhQtukBUEZi9U1i4XnDorp3LRJqhL' },
  { name: 'data visualisation', map: 'iMjoicWT1z7UBN7CR4RpxUsWXr4sBYpWj6Vw5yiR' },
  { name: 'telecommunication', map: 'aJppwWtjS8s8pTaQWbVMBZ5o3ZuUy5E5oy91GKs4' },
  { name: 'communication', map: 'EpiWmYiktc8xbqy6BptT6RcpkY18y8wozeJfpP4W' },
  { name: 'decision making', map: 'M1xxpoNxG5z56B7KpYMJtzdFDLCcJFp4jnTzogdK' },
  { name: 'problem solving', map: 'd2JCqrbLWfvJhRsZxJr8sQ5k5nZexSMLYeSEAN2Y w' },
  { name: 'human brain', map: 'tiiaUe5VgTR8d4GfhqEGPuz9nyp2RTxYJqVozZyx' },
  { name: 'strength training', map: 'zEx8zqZEC6xkyzDCLjntupyeowbozatLj4za8kLd' },
  { name: 'dermatology', map: '2mWgAsaxrkqVBHZZposfqPVuV9sqfbxpZbBpSyuJ' },
  { name: 'chemical elements', map: 'neASa3HWM7jNvb9H3kK1pmpKV7pGpQzT7CKdJ2sF' },
  { name: 'quantum chemistry', map: '9pPZDyHQf6tkHatDQZH7AGBJwehbyoZcmtApPHqV' },
  { name: 'molecular symmetry', map: 'PynYtrYix5pjppTuP8yF6kKpxK5nCAfmqmVp1EAC' },
  { name: 'psychedelic drugs', map: 'x9dBkz2cjvrWKzF8zyALjeJ3uqgDqw2ds8KorBZM' },
  { name: 'nootropics', map: 'zH94GPJuQrQuHJ8LdszFgsEibqnot6hMLBGRqy3x' },
  { name: 'fortran programming language', map: 'rfDQSMASMc8HbKKkWzR9guNAs8RyNyEzY3tANEdV' },
  { name: 'racket programming language', map: '1mak5mvoUr33bPPcyQ576x2Nqn7mgZ7gjMxxkopx' },
  { name: 'prolog programming language', map: 'Y3oKZjoCPExGwi54DzdxzgiCazgHY4HMRFgwro2L' },
  { name: 'coq programming language', map: 'Vy99syjATBC1ykDVzuhFfrqcSUDoRM3QKNkp6Xmg' },
  { name: 'applescript programming language', map: 'aFwKMDSmytpxyV6rGHVU5PwBdeVG8CucFrsKxNhg' },
  { name: 'agda programming language', map: 'R3Svqxdqga4Epw7qsaXpRyAEwLx8HRsNk3xhu1BK' },
  { name: 'groovy programming language', map: 'TBT184Rp9pExuypfNjVkN6wQCs2ZNuqVqoFkGsxU' },
  { name: 'd programming language', map: 'FQDyRm9s9ynq8oToMFtAystowVSCmzmaspbXdi4z' },
  { name: 'crystal programming language', map: 'rzhLr9ZSoPcFYUk7vzWYpkBcWgRW9xqNnmBsvszJ' },
  { name: 'companies', map: '9YapszJmUktoexvxU2cNedCSFfbKCvPY2zmYzmpn' },
  { name: 'unix', map: 'tnBjfWixxzaxU7G2ncpZUqjDS8qnFFx5ZrqdTRLe' },
  { name: 'zsh', map: 'hyytPyvKEHFpdtnqxWNCqe96TFKM6qzDM4NRj2vd' },
  { name: 'embedded systems', map: 'CiYySPyT5VVzs4qPrbZb7dCeyyQR8qXUiCJKrz61' },
  { name: 'forth programming language', map: '1rzLpZky1yMNBYw2oTGeroXs3ZE5azCskzgXN5rG' },
  { name: 'typefaces', map: 'ftrsbpaLcU4HiSq91BTXuBnsUFmrh7iqavp6UsVe' },
  { name: 'colour theory', map: 'axdxvXcKwqeCRZuza6ydGkEEHX4JL6gqN8epaMky' },
  { name: 'material design', map: 'VwEkVbyq9uscxwXeCvx9t6T4VK3vXsR9ppESgRiH' },
  { name: 'arch linux', map: 'kqZieHKS6X3WNH6s9Ncm6k2GcSCAqmK3fnV6RALB' },
  { name: 'fuchsia OS', map: 'DVVBs4v9UTRzs3Mtqxm7XPxrZZsVAHp9dRnTde6ss' },
  { name: 'DNA', map: 'jCBnzdtWzgAzTymbiFrE2kz2dZprYfyqcXVvdRKj' },
  { name: 'human development', map: 'ow1zPpszMHbs4RhmxaL49AjXiVVj5FznyKaLW7hy' },
  { name: 'bitcoin', map: 'u5DHRfRkjPMTTq3vkXRsyVxzZneUp8PJCYsT1RNv' },
  { name: 'serverless computing', map: 'sE1K3zi3i3WRAXTZm7xXMmFCmYCGm3vNo2N8zakW' },
  { name: 'google cloud', map: '8zzuxmxqNy2FKquKzXi6mP5itqQXBq137BBsNA3P' },
  { name: 'microsoft azure', map: 'bskpRmBhBQvN6KDV83xxMPyZspkMpwtpvUykMxpZ' },
  { name: 'sports', map: 'tAtPtzcsKv7EqcYsdu9yg1dZxqENBen99QNznd4z' },
  { name: 'reasonML', map: '6ptBAZDfr2nkjfSKFDrzhXA4sSaFE45dsFogq4ug' },
  { name: 'time series databases', map: '2MSAaYJ2x3CT9sXdNWJV8hupqHhykRxy3MAVikaZ' },
  { name: 'apache cassandra', map: 'Yg6yJKxfEVLwDVpBDXzj6KioR4LPpsjJrLJiHUjJ' },
  { name: 'mySQL', map: 'yVaG46dqLUEx9CqnxPg6Yxox9xAFPXTivv9eMr9M' },
  { name: 'SQL', map: '3hMcGXwc7Soh1TQ7cxsGTrUHeVsy44VxSgzzyQ8t' },
  { name: 'geography', map: 'n3asxAHFCAf8Wt2rHzuwywyp4zVysSBsYgoZAzVz' },
  { name: 'countries', map: '5TGyJp7uFGgKvSNeLn2WvAfsp4vqBMWHcWSdwgFi' },
  { name: 'travelling', map: 'jkwbGqz1PfHdpocP3mCZ3UK4WhxZsKVtsSM78TNL' },
  { name: 'nomadic lifestyle', map: 's17kEWsr6EVWh1tPXzzkU7j9YXAeXqTFNEueqNDX' },
  { name: 'digital art', map: 'ejh17Rcsgb7uUktwBKNdJ6hPWdhqNs1ryVWanxHL' },
  { name: 'comics', map: 'DjjdS1QM1e5NU8QpoTQyFnTzL1fvX7Kh7PhDVhJV' },
  { name: 'application programming interfaces', map: 'ej1akzrEaSC7gqgoN2zziknngUCB52ePdNZ4iKeH' },
  { name: 'peer to peer networks', map: 'Dwx4vCp4qbBuqjizyz9ks2qsSGBRQkvpBMMDPsxT' },
  { name: 'network science', map: 'pSNmmv1BT87tTufm4gb8vQiWBLsix9L33AuzNfX6' },
  { name: 'network topology', map: 'qsGxmY5KYwWw49yFyMMxNmRfszs8swqCEiWg77D1' },
  { name: 'board games', map: 'pQ8AWbKujG7gELUUC2bU4Kr5taBEvap7op8HNrsk' },
  { name: 'computer games', map: 'jYd3LyiesypMyNhmx8ZuVuC5USXNRe8UmDFFtoQq' },
  { name: 'card games', map: 'JZzDhgP2sktZ3pD2NgouS6ppfRsPKKm15Un1ZtMV' },
  { name: 'web games', map: 'nPYTxXLdbBu5ZmHJ3hjmycncFPnJqoxZzoqpzxXN' },
  { name: 'Xcode', map: 'Lp7wtsS7quM7Asapu8JGRjZaGpbZ8iFLyKTBpi6s' },
  { name: 'messaging software', map: 'snLyF6uVBXf1YJMzsoSzZNp7x5gJyU1zGL37bgyR' },
  { name: 'adversarial machine learning', map: 'CKNLj36vrZgDEVuxtxCpVpsMu7sCpYxodLqWUAaw' },
  { name: 'datasets', map: 'Nkaj4VVVVEUHzDqzpYgQonxqe6gNxzqqqSAxpfAn' },
  { name: 'numpy library', map: 'buGeFf4ms9LDv1ypqL5gXX8UzvbnxjjxMqEct7fp' },
  { name: 'caffe library', map: 'QvtUUHWYL2TsoWD4QbrW8DCg8Fxy7yzmtWtqFG1z' },
  { name: 'politics', map: 'jyGfsb3qosZpu4DgCnUxDNfwcCjhLjaSToVyCdxZ' },
  { name: 'v8 javascript engine', map: 'SZxDsZmsX4p4TE4vp8zJrfWPsQpq12qZfAu8W4Tz' },
  { name: 'selenium browser automation', map: 'FAmSCxscVGxr7yBtbqrmr3yFPQpBySsaxW6U4esV' },
  { name: 'static site generators', map: 'dBxLhUp5YsqeYemH27s5N1k47PMqvGzqDyys2UDj' },
  { name: 'document object model', map: 'Ex1kqyApUnyCk7AXbGiXBb5QnDdMNdqZz6spxjuG' },
  { name: 'web components', map: 'UCneg1U5LDqEKQpHrSqwinKbcYSwVa81kuU1Qpy2' },
  { name: 'web APIs', map: 'QJfedTmQLA2E9AxRTvcN2WRqgksdz6dt4HzqSsd5' },
  { name: 'progressive web apps', map: '3qHSpptz8zTyu2T9duba9f4ZDTyyz1JG1VF7bADQ' },
  { name: 'site reliability', map: 'MRk5HqxJyTnd9ZEasE7a8otHWsyWxj6sC3go4VEs' },
  { name: 'internet', map: 'itQYpAuPHakMuEUeveWedDqzTFaoH8MyYpd5AmVD' },
  { name: 'chrome browser', map: '3uqHrLo8E7tCqznyNp2xtCLsWkT9qRtpwwFyYTTR' },
  { name: 'safari browser', map: 'vzpg628sGAz3c67v6eKCsqxzth9QNHpm4sHdZyzy' },
  { name: 'economic systems', map: 'RjPSsBxogK3XdZ5qmUwdTzMK5yYcchki1DRLVxPs' },
  { name: 'capitalism', map: 'zqsN7z7HxaroGxyN9Lyz42xhDyqNnGHEUMT6LYbN' },
  { name: 'trasport layer security protocol', map: 'p9uXx8nMg2eXj8ehzPbi3ypKZenpxW5b42rXfdz6' },
  { name: 'RxJS library', map: 'rdUzwvGv7Gpa2z1ZhPrzDsmpR6D1nCL6VN6zFssB' },
  { name: 'ember.js library', map: '5ZiWTQfkYuPuGrMQoHKEypmUzPVzDz1xrNbTo2ah' },
  { name: 'cycle.js library', map: 'f5P1ih7XHiUGkoLsjtpxpGa3ySq8S9FKjEW4WusC' },
  { name: 'jest testing library', map: 'vQttqzUvfzbk97qSDhtEZiFFmNpb9fy6XxtKPyz7' },
  { name: 'particle physics', map: 'GwBsZB6tz6txPiz97xyssBsxDTjKwy4J5seF7uvC' },
  { name: 'minimalism', map: 'vZ3FssCtMk5Q8HjqW8Wtcr178dJ1iz2HyHQEc2kj' },
  { name: 'success', map: 'kPVKqy6Fv4Q6VaUoiz3CyppXwyqwXxcB7rqVeUWy' },
  { name: 'habits', map: 'Gi2ZNWPkruFk1koDUfxp1RNzzsuxgXjsSqjqyF3X' },
  { name: 'creativity', map: 'XaEipc85MqxYF3r2orNF7Tq2zWx4NnUzmS8VpkpW' },
  { name: 'microservices', map: 'u3s6kTD4sX1tygnSfVWyUY8EymCAiVn2DKB2sqjq' },
  { name: 'F# programming language', map: 'vnWZGKYDfbCy1deTxpyRorPqvexRgJvu9pL29KcA' },
  { name: 'research', map: 'q5cR3eqQ4gw2CKfPZqjZbA6DzrSrmvG544P3kVk7' },
  { name: 'cellular automata', map: '1HwFH9xRqub42VjeSuUiz3RqPNX2dKrZS2R3bZyg' },
  { name: 'fractals', map: '5pycd6JxCpdPKLwqasU8z2vGfsLss2qvDiMZaGjs' },
  { name: 'business', map: '8HjHL78qbW5weVG66sypetaqMJdVqgN8Xos6gaiK' },
  { name: 'terraform', map: 'wKsz4Z2JxPeriLwQ2LRqHpGUzzP32vphfrsT92SH' },
  { name: 'automation', map: 'rF6xqdrysn9UwxgFmsDXuvLUxUn9JzxmdLCzxC6A' },
  { name: 'life', map: 'jWyb3PTvbKszgorVZrKqRRYrdxp8PYqxVySbtq8R' },
  { name: 'cooking', map: '9rHtshs5V5begszbXgBekcpYxJ9aRaNUszxRAbbH' },
  { name: 'mathematical finance', map: 'MbLi29ZzLUxTpGtxvJDu2qrbhbVCc97Z3tfz5UZS' },
  { name: 'urban planning', map: 'urXNVRzUE66CUzPYuTqTBDp9vUJGnRVVWvA8ynz8' },
  { name: 'transportation', map: 'tF6pZdQMF3yuJhyzJA3XuybdXPvGX4DUHKttdGEb' },
  { name: 'solidity programming language', map: '8EaMoYcRYzyLAkJ1EUSWQFxfpdQm4hqmcyjhH7es' },
  { name: 'finding work', map: '7GqWMZcpv3pKTxzopsyfJsQmBtdi7sy2gkuRvrjx' },
  { name: 'web scraping', map: 'M1yNy1kZFCTh8PN6mqQP3vgvTauTuquavqSjDkQZ' },
  { name: 'aeroscpace engineering', map: 'TTXSvmsSaVq3JpJy8ytYbbR9w5vxoUsNmds5UxuW' },
  { name: 'rocket science', map: '8M4oUjpGUN4Lco5DRn2e1rNEmDwmCSQaXEgFz7jt' },
  { name: 'astrophysics', map: 'n1vnPsnyJHXfr6e9cuRruLX31Y2vz27aMAqkXmHV' },
  { name: 'search engine optimisation', map: 'u6KUXjQVKuZtdywmxzyJ3C1QqR9yCUkjadNzsFmU' },
  { name: 'product management', map: 'sCFMbq9sV42TeFcyXvipGFavex3Q4MbAkRgSsgkz' },
  { name: 'zen', map: 'uE5NXtsrrgzDyv6h84txcgYuAzWeRfPFgeGzUcB1' },
  { name: 'new music', map: 'xqzDSkip6XTazQpYRsgassvJFDuu5oPzqNWicUhy' },
  { name: 'monads', map: 'rQrWiuxCxWdrWjKYDRyJE1gEeRkdJf83rYppJxuP' },
  { name: 'growth hacking', map: 'KvsK9zYjVv74ktb6TDe9gyqn1hQMufNrqCHgYSCU' },
  { name: 'big data', map: 'ieZsPsxR6Y3D3bh8964SV4tAy9mwFJczAx8AVEFX' },
  { name: 'design thinking', map: 'CXgWGayx57yBV16aaEEJYnN3hqjyw8FJamnznpgv' },
  { name: 'string theory', map: 'GDsxKqmEzJ6utJAaicvy9JjkqyfDm5GZDzFVMzUR' },
  { name: 'CRISPR', map: 'Hc2RYicxJSQwMmsTS4dfVyDhAbmKbkJYkxcy4Dsk' },
  { name: 'accounting', map: 'xbjRCSkQDphpvvvZ8FZcgCazpajSKUkEV8uTz7pE' },
  { name: 'art history', map: 'E992zZypjENuxVKaBJ7cci2zQA3y3sutKSf7qkep' },
  { name: 'ASP.NET', map: 'zkKCp577LkmWFgGiNXbBWMspnxyeFjPBfFhmLsBz' },
  { name: 'seduction', map: 'Jr1K2G8yAygxnRXQHYLqqeHnW9SbEna7XkVBzZUb' },
  { name: 'relationships', map: 'FdxqYCv77bAF9ebSfAtb6Afz5BEu4qsWLzJJ4UEk' },
  { name: 'python libraries', map: 'kDFfqVBWhK4htp3sQLpLmxgGLxhTCk8Qx4mqGRaR' },
  { name: 'flask library', map: '5Nw5QGrzySmMTUg28CtuBdMseu1PqnzUCRnMMAA7' },
  { name: 'powershell', map: '5JeHP3cTTTX3eiLnPXNMuT5DWxArTHLBoqqu5Rnz' },
  { name: 'korean language', map: 'Z6s9qKbrTiL5RpKxtJSy5gbPV3odyWsscF4SW4yz' },
  { name: 'graphics processing unit', map: 'sm4Fhdd4tkWngabpYRSjf5kjp3qtQSxpj73iftpc' },
  { name: 'CUDA', map: 'WicsHkTZ79jrtJm8sqtbHygr8qsJSa8kGKx68KN4' },
  { name: 'OpenCL', map: 'cPLzpxwsapXvTE3viS6TJesH6WmnV2uqG2Bueqi4' },
  { name: 'apache hadoop', map: 'S2z8Aw6XDpzg4E3TGSSbFshFyeKqXyZYfqsqLhax' },
  { name: 'bayesian statstics', map: 'towrUbKLgp99RYxozHzvpL6ehVukW5wgRsFqQQq8' },
  { name: 'AutoCAD', map: 'xS4WzamyvPgsLigLnGLDkuoPsQWvnCnAthd7vBZz' },
  { name: 'computer-aided design', map: 'w2Pp8spx2GHSqMq6TNQzCYVaYPZRLJk4ppaYSrqn' },
  { name: 'encryption', map: 'qWEzhMurSUCvDyqXq2p6nnUd5cdKSrq6vUnpbNrp' },
  { name: 'nixOS distro', map: 'AV2oRx64iruLUUb8ptdy1kQQmady8abtt2sMfFBv' },
  { name: 'dynamic programmhing', map: '4o1FEfJ9UgedwzDqH4Tkhbi4PDx2THyeCESTahgS' },
  { name: 'quantified self', map: 'WpQM63QofNRcYsZqDqGX3tmGkRAGWoqRcMKEe7Vx' },
  { name: 'project management', map: 'jxEppQQpXnkC7rnVxW7FpFTy6zY7yectRR2JbySw' },
  { name: 'cognitive science', map: 'hJAyyxuh4wbGdqAY1ym4TUiczcFLZBQqFqurTXyP' },
  { name: 'signal processing', map: 'idyoc4NFVVdknjsv4QXzD5t4uU6qs5pqrWg3pryi' },
  { name: 'video editing', map: 'puirbm5C52rK7XMf8wfKqquFddMq6iJyQSwJcyFs' },
  { name: 'personal finance', map: 'zf1V4zVDNjsFAcY7K3Asaykmjvvxzqd2cp4Z2dbA' },
  { name: 'alfred workflows', map: 'KRC43JvzgP3YDrzzeMvkSN4TRWpTJokcLqKz6BRs' },
  { name: 'poker', map: 'k9Z83iDQqGBiGxckxXqEnf7Es89U7ymcJNGjzits' },
  { name: 'productivity', map: 'Typb7DYzYpY5TaizNhvDvnRvUXp6sEqeZNKquSmz' },
  { name: 'more', map: 'YyJtZap3S6BLzLq8FvBqcDM1fpzom5JfeXripa9w' },
  { name: 'courses', map: 'RxT86Azyw654TAsqww7ueqXGioFRDxx63r5ddXAC' },
  { name: 'NewSQL', map: 'rQQDNz1gFCUB16EUvh8oHLLHzLL9hTmyLFqKHk1d' },
  { name: 'cockroachDB', map: 'Yu39NVsf7ppg96BDKACfFsti7qeZUHyKA7m7diLR' },
  { name: 'ukulele', map: 'FAcVAKt6QvNKLyDqwWZfyJozp6YF8pJRz9cxXXxH' },
  { name: 'differential calculus', map: 'JEQtTKqpYEn1kHwx1zcPxV2xZabiXekei9GUpYbS' },
  { name: 'gardening', map: 'zBgzq6H9Hz8S6fyB9rLtHNCYN5AXixNoHL2EM7yL' },
  { name: 'hobbies', map: 'sHxGzRAXfBV4pTJ8DY9jAzQDhZdABChxAhcyfp4q' },
  { name: 'homotopy type theory', map: '66wZyXSpGgj6qxtJoQWqGzpskJtgYHZGV9nVBxrp' },
  { name: 'genetic algorithms', map: 'eyXxva1VSE8WZvKJqNgF6tXMpRqt6KL44FsizaFF' },
  { name: 'sorting algorithms', map: 'wfdPrx9rsUeUpwwspRgsM741LKciWLMeUev8ML1u' },
  { name: 'big O notation', map: 'wptdyX9aF7U63EaydGsif5s49ypXyCJ5qq2Gyduh' },
  { name: 'anatomy', map: '9uv1CLtwKkZZA4AV4q5zmyenvRpFQsryP6Z1iW2e' },
  { name: 'logic programming', map: 'DRHzPabqxynXg22yn4qyossXjbdx8y8sVZkWNmjx' },
  { name: 'constraint logic programming', map: 'YVyRYL6u9aL2KyKnnr8TDKA2Vwezdznour7QUMSs' },
  { name: 'IDE', map: 'EUFs4RJNJDkqZumUf3T6N1Kz5q3C56qeKSVU5xF7' },
  { name: 'optics', map: 'gweVyeFwnDFyeHRt23ngov2uGN1zyRTYAy83ZMkW' },
  { name: 'clojurescript', map: 'gDrV35KLRsdT9Ajxvr7EnN9yanPrgTx7LRzmfBUK' },
  { name: 'mathematical optimisation', map: 'qBdsvy3mGCnqNNPxwnAhb4u8EgFmBwbhKMpzxUXR' },
  { name: 'addiction', map: 'UK9ieAfPpMqTHzAwk1o7hL3xzUhnGHat3KUrLa3n' },
  { name: 'programming practice', map: 'bF5YW76MmjiqqesqcYAd8SWU1TzgqxbczE7q58y1' },
  { name: 'digital video', map: 'CWPVHgTCxAbA46d1yx9xtpLE5YHq7QARwcRFz6vC' },
  { name: 'quantum entanglement', map: 'PyWDaJAKxGEsAoSUaEuXk6sBm7EHxiMzxsDzmeqJ' },
  { name: 'music theory', map: '9M9ppukSxsxszGRXCj57E2BccmpfnMNmzgyf8fDZ' },
  { name: 'polish language', map: 'cxUxDZYyPPx51mkjiHiKcQsTypCfszxT6zwFHoSy' },
  { name: 'quantum information', map: '6nxrnv5quSLhpb7nwdAJ2BiaKFDxE6oQeeoHcW69' },
  { name: 'scheme programming language', map: 'Srv7FNQUqgDWptsptFWohQ731RqpywWZTJe8jyqZ' },
  { name: 'meditation', map: 'EWHvLZs2foxPwdafxLiQBZLRAxepeCEybvzpzGpv' },
  { name: 'cybersecurity', map: 'HstinnJz9VyxRxHsr3sAQzCWPuFXqLYBMzkX5AoM' },
  { name: 'knitting', map: 'zLUJZWvkWHtpxzjqnsohVLwbybupKvMY1bnq8FXX' },
  { name: 'discipline', map: 'hy1aisDzXMPUnRuKBYdxspJdpzMyzJBVRB8gafJi' },
  { name: 'firebase', map: 'sFtGYoLUFVQseF4XtsgJJFfvCPLqYiyDuYcW2Zi9' },
  { name: 'websites', map: 'BxoJyqgsfvB2J9rrpm1zwzjuKxPGUrYn6YDpSGbH' },
  { name: 'vim plugins', map: 'XazZqbK22FoZhYA78ZWiYzX9PrxbzWSsmm9u4QCu' },
  { name: 'recursion', map: 'shyEmRexQbPypbYYtjqoqPqA6ADoHvCi1Kzq4UuC' },
  { name: 'yoga', map: 'BypM4A44UVcpNJL6pfPAsQDznQJQX9MVBDa52AyG' },
  { name: 'fasting', map: 'E9893zmQKen9ZuX3vwE8UEJRvjyaXUU8iZx96kpi' },
  { name: 'rendering', map: 'rdgKa9yyxeycCFwbFLsJhHxocZzzzzixzyHQhWgk' },
  { name: 'italian language', map: 'g6YtzQoM9Vp7QEQaVzqtqqv3pp4JSXyCwVcTua1S' },
  { name: 'game engines', map: 'bxSEPduhsyxhpEsq3aDWjey4naXLsLTjdjTCqBGB' },
  { name: 'code review', map: 'oWJuvGLv1isvtjdxNwyfieczokJ8QMq4fwMhJ9KC' },
  { name: 'youtube channels', map: 'N3Hx59tpFnfuqP2DhgpF487Be59Mf3gNWejeFXQ1' },
  { name: 'orbital mechainics', map: 'xy7sgqvqtpzcNTkkqEw2WWyEzkNYybte8MEPq9ip' },
  { name: 'drums', map: 'Xhz5zaPjzqdnqK4gZiQyxoFMaDrdR6DGsj9tTMqk' },
  { name: 'arabic language', map: 'Mx2GVkpwTr6YasH6NsRqcxN9uvXG6aHyob1A61vz' },
  { name: 'sleep', map: 'rnugS7eKcAzQjdzv3VsLUdcz5sq5LvbxaVEKyfSg' },
  { name: 'lucid dreaming', map: 'sQQ5QWyEXS2eyt2qxsHKpqWeXFmsBPfdhHSruecQ' },
  { name: 'ES6', map: 'rNhr9Nq5D6yWCM6rjQLYyLyoxtomM6yK62VZS4Ud' },
  { name: 'real analysis', map: 'AaUBkh3cjJiSaQPiuSpzxrTshkiAZWrhUeyFYy7S' },
  { name: 'complex analysis', map: 'YafLyafC3bkpDQHFrktcGFypCGWF2jNxtF7rWqps' },
  { name: 'functional analysis', map: 'ScFgoYotBwT4ucQSRz1Q1daixxu11JDBfzjHGz4r' },
  { name: 'measure theory', map: '2qzgDcLAps3tWz2xZDdZ93cDpXzbqGzZ7WyzixTz' },
  { name: 'RSA encryption', map: 'Eqxwf41jpdWebzrx5xuzGx23dyDqgETh8SGQfuRc' },
  { name: 'basic income', map: '4Xd3Y54pbQgrujAoDSpoK84pwp99mvDduuw9km7X' },
  { name: 'veganism', map: '54KJXyXG2U6zioYe8XPHx15uR2xWb2pKUqhYnuxH' },
  { name: 'human rights', map: 'aU9xyy3HCSQpoDaL8yzyfyb7ep2SiGqcw7RinZWh' },
  { name: 'rights', map: 'PqspiLyuwys6yetWfGUqoqpqfPGzRr3osziXPq4Q' },
  { name: 'OpenCV', map: 'z5Q6ZVzx8QBAJyocALLH2xY9LyhWtapAqRXzVzNC' },
  { name: 'hash tables', map: '64QWJLf2vFoA5xJcP3BXvp3ak1VXkpWTJhPyqaev' },
  { name: 'cold war', map: 'Udm6Ch9EyzcmjCxztVGzRshsDbMgHNEhLMKyBGqc' },
  { name: 'facial recognition', map: 'niJKPUBTXEr67jrMUCGAyhmsWqmhygA2uR1LN3i4' },
  { name: 'books', map: 'qhfjsvdEP1y2zLoG7vDEPXkAjxTj4dSxyvG3aRkz' },
  { name: 'research papers', map: 'Cny5WMjy56ay4pDopou6spjQiiAbzusp9XuW5zpT' },
  { name: 'images', map: 'csvpLeXgNZCjCsUvQs1rsNz7zUx2xCuLUhqUFzWJ' },
  { name: 'pi constant', map: 'KpipjaazYYCyxZVMH7mGWkKewgNSGK8AXYyaXMHN' },
  { name: 'trigonometry', map: 'Rnex24pLbmpMpYzuCG1y4uRyjp88Hv7ExoLLyJJK' },
  { name: 'music production', map: 'ANRJHMcssy9Xq6HAHqbBysQm9nZg8urAYb7LVZSD' },
  { name: 'reactive programming', map: '5QvfTXNvXYqJrZt2dZqbyezpbPyrpqHWMrowyLHk' },
  { name: 'advertising', map: 'cFnWJ2rca87n6qtdup8s9WZpqKqKXHUvs1JXR2qu' },
  { name: 'differential geometry', map: 'LP1CkYiopV1m6NGvnAARExdczkzKFtzqzAdsKiJm' },
  { name: 'blogs', map: 'qy8DtEVpEB3DrEfPxtirt8kPqCXnms8ZgAX5wxMc' },
  { name: 'humans', map: 'g5KxrnzbC1qsmYhxXAM3xMzoWtCSx8624REAZbKA' },
  { name: 'algorithmic trading', map: 'xAxBwBvkyhLn3T8TeWG7DSFzgELFQqGWP39yydEh' },
  { name: 'ancient history', map: 'fSJLUqJyrAMRnmZUyRmkG1Z2Dqur8ksgCfREbaqd' },
  { name: 'augmented reality', map: 'yeuzVXx6fhwm1eYY2qq4xCwzM4mDq9PQTsdC9AP6' },
  { name: 'data analysis', map: 'pFNNbr8xNYs54yriRqJTqpRzhNzFyx3RPiwGoZHa' },
  { name: 'pandas library', map: 'ypjyzY5mTyzWdjVy17YNhxMwGxF3jdadaZnsCqsx' },
  { name: 'aging', map: 'BLrVeozbNCFtRsEbLiKz45eGhZj24faeCsdynsQZ' },
  { name: 'longevity', map: 'GCmZHaoqfrLTvqhrQ1Mx64SxSqqcsATquYsyGpip' },
  { name: 'ecology', map: 'opidGY4iHZYYPhsCVpGML7yWCezGB9VGVSKbt7dY' },
  { name: 'literature', map: 'SVLeshoyVsDPrwnk2xz6tYKa4pD2zjYQEu1DmBEG' },
  { name: 'US history', map: 'nQyyLaE1WuiyMD2yFLTyyezy9rWBV2tYZe7fRiXW' },
  { name: 'epistemology', map: 'yBFNRBszx4CsN45posUWEJ4xotNXPdKjJqMnSysw' },
  { name: 'mandarin chinese', map: '7qFbcMQGsxwJSrhd5BTfgcmPp4fsfUjy5VPX9UxK' },
  { name: 'woodworking', map: 'ysZxjMan3cKrci4vF4ipEtvqs3wpxrqqAnUVLpGs' },
  { name: 'supply chain management', map: 'jkSGn9YRpqLmssY8ckszBZLx36KTTHgXAEvWtqcy' },
  { name: 'algebraic geometry', map: 'ppSeqEXoD9ZqTyeoviWzA7VFCGv3evZvKpPNPqDP' },
  { name: 'algebraic topology', map: 'VMQbSswp6JPZ5Cx3YEJ4ZVpBPtpnyDp2D3y4utTy' },
  { name: 'computational topology', map: 'uRUqHn8sbzMtpsdF1ANPnPg9sq87x5dnXfwLXTqU' },
  { name: 'lie groups', map: 'sn869ByU4v1Jvq4xcMNC4ArySxqAFWk9sexw9hNr' },
  { name: 'abstract algebra', map: '35xAsH2ays7oB93yqhTjCDAhK2B9E2yGFX6gZm7i' },
  { name: 'morse theory', map: 'x8esMe29zt4LFqUmEaHus8ym3Gjkowsya5sxHmoA' },
  { name: 'motivation', map: 'TqsqB2G3zmtsq47gX5GdxCVsJTo1AfBhe4hUr7MT' },
  { name: 'physiology', map: 'zymyd9774rLxxKUmz6VZAHxoCYRpmB36VTbx7sbs' },
  { name: 'emotions', map: '9vM5pz55ypkLzw2W5Epq7w9bL1egMmXbcxyM4Emb' },
  { name: 'happiness', map: 'yDzksCE9TATPeVb3HyAsTJSsRtqQXyQ8xV1Ydinc' },
  { name: 'search algorithms', map: 'AgnjCBHsB7xdQ61qP7Ncxp6FkaDkEXqartpjYqRY' },
  { name: 'monte carlo tree search', map: 'fegEqsZPctyE5msMWTTwqWoc8Lp9GUqaap9RF7c2' },
  { name: 'bulgarian language', map: 'qHzSmeGZy3JuFzpCZr4aqFBJ9ezkqydP8nsNYrdV' },
  { name: 'computational neuroscience', map: 'xrNMAaphotwt9vQqmN3EZesmkgrjmuDqFENjvRAY' },
  { name: 'dutch language', map: 'x42y9yVztRqbMBAyQH3nCjAunkXTwX339xQmMrsh' },
  { name: 'stream processing', map: 'sfVx6d48q9TANpwrVjD7wHaSaCBncrpxdvXL3iTv' },
  { name: 'apache kafka', map: 'HnW2s1yS8sRxhPtcQa8ARmMeP7kLR26V3yAx9DnK' },
  { name: 'norwegian language', map: '5p1Bs3PmWrGwzAeW3zwJPkxshctFQqjtrR3ELyNx' },
  { name: 'tmux', map: 'mk1hLazUx97D8tymkePWZPuwhY2LCFDXTN4vF5RV' },
  { name: 'spreadsheets software', map: 'sBXqYdu14ZjtwYMs3yzGZ8PMzsakWMupea4sJCqW' },
  { name: 'excel software', map: 'psD7CyDsn1PnCNq8xpxK9983oC4nDSYGbN7xUJJ8' },
  { name: 'weight loss', map: 'efwCXEFZDjmZF15HijRqP5zD4yhKYt38i49FBRGY' },
  { name: 'visual basic', map: 'XQUmBZqojY44pz2TC1g8xwxpJnTpRw2GcsuE7Fyq' },
  { name: 'chef configuration management', map: 'AoWytgNd5KGWqk5w1C1h7yfUBRyXZeAkdqTwidRg' },
  { name: 'interior design', map: 'LkySryeJNzstsCpvezSGwjXNyzmHCSzUxfu9eoEd' },
  { name: 'differential topology', map: '9QEPRzZwVhhvG9prGkYZhSgHspcxgk9noPEQPqzh' },
  { name: 'music genres', map: 'VCg9zzcqg4xxrkqLBPXUjL383uvpZv2KQPHzsAkf' },
  { name: 'jazz', map: 'W1QuT2BtpPuyegx4N2svHx885qPXi6kjFz4Brcnz' },
  { name: 'classical music', map: 'sf6D2ZsdvDhHbBquoKmfP6fdAiwD4RsE1Dqws4Fg' },
];
