module.exports = {
  'AVUfxKqZjL329qksB8jFMpx6zDA2tpQDKGC9v1RW': 'learn anything - mathematics - algebra',
  '1qepKVwZ5z6HqpoBUr2ipQPbivrJjir3y3UPAGvP': 'learn anything - computer hardware - 3d printing',
  'CWsQJ418QKxqEztQEYyozPWHiqxEK9JnZBgdSbpz': 'learn anything - virtual reality - aframe',
  '5YecPzsqehbb4o4tvaXc6uykmqhzar3AykvRqpE5': 'learn anything - art - acting',
  'SLXSGkt642jAz54xrVGEFLVtZmrrB7gzGPohtngF': 'learn anything - biology - abiogenesis',
  '9GNqw9qRvvg1A8Jeo9EW7fm8bcyWWtjKD6i6pa6w': 'learn anything - operating systems - android',
  'qApdnhTrkU9PehVJNxnYKLxpx1qchdDk6S4wFp33': 'learn anything - tooling - productivity - alfred',
  'mpCNfLpJ5cAtJbUG9twTjqQoaSozpJHzXSyDMr3U': 'learn anything - mathematics - analysis',
  'uD7brAJerhs2xfCrCjsto7fXj4HzkUBrvQUfEyZ3': 'learn anything - biology - animals',
  'nu6BzRKfbifbP1pF9SxusxeRK4SqMBD4fPAjbxNi': 'learn anything - anthropology',
  'Q6r66iur4UDMMzdTtbCJgnsYaZbDnAygh8tbBMd3': 'learn anything - architecture',
  'LqjxehvfzXszoTjqzLTdcrfwD6c4mSFck9PDgxD8': 'learn anything - art',
  'xFxmSxUn5zw5FF4ZoNqZsCGjvszFZSEHhy5PuHfE': 'learn anything - computer graphics - bezier curves',
  'zi4L6xyTss5zyiBkw6RqAqUhzaBZgpXNQk2UNA8D': 'learn anything - chemistry - biochemistry',
  'syiq5vpE5n7gWTqmvja6v6ivhY7EY1AP61qpz2PE': 'learn anything - biology - bioinformatics',
  'VbTJQGhPcBZ7kWwXri8sUd1kTSQuAeZH8xkCtTgp': 'learn anything - biology',
  'M9oKwx4cd9kzJqTpJsoUaqpGo2X2bvfwdp6ekodK': 'learn anything - computer science - algorithms',
  'z8HaiMkaqK9Ri8tJYgKGAv7x2TPiwkRNnKa73ZzC': 'learn anything - neuroscience - brain computer interface',
  'KdeMPbxs8KPixsa5YUq5cphqJnQg81vpHaXcDX2i': 'learn anything',
  'uR5wuu9guh97btPqQaRND2QPu4sxenfzMRNNPsyB': 'learn anything - web development - backend',
  'YopAYPxSrgy7Pqvs6ztsEgqyHeXrCd5uRQY1zzUs': 'learn anything - web development - browsers',
  'JzrhswUBxsHBaPtQNHoxPvWApsUEenW4EpeDbsHi': 'learn anything - art - animation',
  'Cy6YFfoRFvBbgMMWgyN2zaqhj9KPjB23fwxvN2GB': 'learn anything - programming languages - c',
  'NRbzKJDrEKKWK7pvqSdpBCy2cscxZ1ZMizkxzQik': 'learn anything - programming languages - c  ',
  'wzysPxEVDVNYXebyN8Sp9qAg4mQ56btHbicx99ac': 'learn anything - artificial intelligence',
  'Ay3xy8VuNPMZyDMqzDwVQ9ijtJQBjpm82QWzinA2': 'learn anything - mathematics - chaos theory',
  'Xs5qLyzR293qpAZLJWY39SuvK2xkW2YxWm61wT2M': 'learn anything - physics - classical mechanics',
  'rzNXGzaSkyjn634xxnSb2jwzC7wddoxxxrB91PwA': 'learn anything - mathematics - calculus',
  'q3CqTsNEX43ovcxU9qoYU3wn23Fro7qbWaqxFULX': 'learn anything - programming - programming languages - clojure',
  'QPRgXSbRCgrkyBSD1xsSH3NPzptQxzwg2XUm34cG': 'learn anything - psychology - cognition',
  'VdpXxxyVpJm7NedoNqt6YnSAsN7RWyR7mzLh3xs6': 'learn anything - chemistry',
  'MxmPsgBTgB8vwS7wcHpZgvTx5fWrdozgZngVpbrp': 'learn anything - mathematics - combinatorics',
  'S76EQdSTiDz1hMJqAtz1Mp3zqeSJy8bytwteqbrg': 'learn anything - competitive programming',
  '8zoz2iumK52ZVSsuEr2bqY2cyzpx7icMS1nMsNH1': 'learn anything - computer science - compilers',
  'JdxG6pPiqvhyyzW6oARy3dr4q5NTFx7oBZCMoodd': 'learn anything - operating systems - shells - bash',
  'SnqXfwJjzbc3Vs5F1tUayBG5RhDxxwTadc3Y6At5': 'learn anything - mathematics - computability theory',
  'p7RzoL1gYA4Y4tzxrGVtRC5Tc1RLB6UtMnws5ugv': 'learn anything - computer graphics',
  'LHXDgxoACw1ykgGsaFFvKsnaLaeRGviV74j2wtkU': 'learn anything - tooling - cli',
  'QKWtVCHyuwbZnuxdtzZhXxs4wp8St7GeiLbKMzQU': 'learn anything - computer science',
  'mCmNsBxeiGdRqYefxaq2HXYMKxf8sFWq92qYtMyU': 'learn anything - computer vision',
  'FPn7sjCxzFEd6mqaBEwCCexNnwoPyFGzu5ySkMRk': 'learn anything - art - creative coding',
  'WL8T66hAmVGunSeX6LoZi9ohx2RRKk1riegeG3kr': 'learn anything - physics - cosmology',
  '7TUvLNzE4aUwzNqXurPdcyenQR5sYx9XsJjYcQcZ': 'learn anything - cryptocurrency',
  'LWuYxsB4TRnH49YymTXqkJQuzpUV8MjembJ4mBMs': 'learn anything - psychology - consciousness',
  'cgWrEEoW3HSA2iysGp2swqphQXSpqVvM5TaismpM': 'learn anything - mathematics - category theory',
  'cHUd9sSPJHjKf81sczwqxPgS7KyJJqzXz1kp3shm': 'learn anything - cryptography',
  'RotqNyXWxoT5pBazqnehMuKLkgHiM32WYqjazgpY': 'learn anything - web development - front end - css',
  '2qFq7j3eSx2Szz3PcKGTbsSbM6psoYYGTErdyYXd': 'learn anything - computer science - data structures',
  'NMjhSs88CAGYpxwsd4CP8mkzMRj5o42CMtDVJhtN': 'learn anything - computer networking',
  'VsuqhhyBK8PAfvzuHqE1DBmyB9xV8fSePsX92ssB': 'learn anything - databases',
  'wqhKt6rDSZrJR5pVV2TpCv4xnHUsYJf3vZ9SbX7D': 'learn anything - machine learning - deep learning',
  'grUmLWNxBRYqRUbRVXqWc8uygE3SLPy7V9tp63nq': 'learn anything - design - design languages',
  'ha8hqZuHbb5Py7LzxWoCatscK9AZsR93vJbyfqiq': 'learn anything - mathematics - discrete',
  'qSpAkmpgvtHK27TFhysj9svBh7fBaZKjuFztc1ms': 'learn anything - medicine - diseases',
  '2ZYrG1D2SizuM5YzrnCNQdNqzZXC1N5nH2aTMbVd': 'learn anything - distributed computing',
  'z4ZojQ2ngJ83LWaew44kstV9f2YX3Huj1pmFUbTc': 'learn anything - art - drawing',
  'UfyzJtYHJtarpQg5YVXVz7vwYjQvn5FQt4g3pq4C': 'learn anything - design',
  '1Gr5QZ6ycqVbhVNahBk6qjdSjsttzxuCz3UVDge1': 'learn anything - web development - javascript libraries - electron',
  'Lf272jyyVyWWmRPpxs8z4GvsxQqGPLfpZrVhYnMn': 'learn anything - computer hardware',
  'zW4mZpEwWk59LkRXCFQCxLCNGp52Uzt9yHFyk7A3': 'learn anything - programming - programming languages - elixir',
  '5HyyfoE5sufZR5RvN9isTCdaYByzxFVhLqpk2MXg': 'learn anything - chemistry - drugs',
  'FHh7spgcDGWdg72U6L4u34VRCrW9kLswUHQoXBMs': 'learn anything - economics',
  'Mq8uxEBieqJSQayVpnN4TWhkqcyvWVxeUF6sxrYu': 'learn anything - tooling - text editors - emacs',
  '6SJjDrFxzofoZjxfpgH5qVryLSYjppJsg28NapzF': 'learn anything - engineering',
  'oTrSaQmHmUvsfe1y2CpKU4xxnXueJKpKGoyWLZ68': 'learn anything - linguistics - languages - english',
  '7wRp4x4AGyQt7oxU2PzZpSEGudSns76n1f9WXD6Y': 'learn anything - entrepreneurship',
  'YpcjTrk8y4e46T7kqFBnTmsEexqtCasGsrbHYTFL': 'learn anything - mathematics - ergodic theory',
  'qNHHXzr4uwFXSHsHsznLkWvXXVskz6hFtjiRKcai': 'learn anything - programming - programming languages - erlang',
  'Qzw4xRpZJLXCBG357zegCse43zFFzkBmssmg78Bo': 'learn anything - distributed computing - ethereum',
  'QgyDiwvEke8bbXKGFQoh8zC4JUkpEW7THSpjPuDW': 'learn anything - engineering - electrical engineering',
  '2qWdikpzGwN6GkfyyevpW85tXxACgjqWGfxyJ7Ph': 'learn anything - enviromental science',
  'vRcTBWAWQsQwUHvqMV9bNZbLDmXGxadnyobphBd9': 'learn anything - biology - evolution',
  'zwrY9ZyZy5sHmRg8HizhVnJMDpxQnxahdkqA3i3G': 'learn anything - art - filmmaking',
  'bFq9JuRH7YWRZpAqwPiUocWsssov8PPqdUGXhVpt': 'learn anything - economics - financial independence',
  'S2WsuUtQp9KBSCz9TqzCpKx3tkxTTB3rmr8yPGyJ': 'learn anything - operating systems - shells - fish',
  'Qruad21hxq43Qw4xHN4gyPZmeKc33cx3BDHq1o47': 'learn anything - health - fitness',
  '5gzqunZqRm8gvpA8K3nYvUmesyyemK5763gwYej1': 'learn anything - physics - electricity',
  'yyhkEqtncydaTup1Bfz3Du7juXt5o5Urpp9pnWQv': 'learn anything - programming - programming paradigms - functional programming',
  'rMqH25BBnT8N9Frhv3L6YCk8NozigyGWgjrgPmjE': 'learn anything - game development',
  'YfXtXRQ4Vys8SZaxwKETATNSWX4rbhHeq6xPxLjm': 'learn anything - web development - full stack',
  'YcsPzMswwUu2QqRzQYytG3ztDyzfEaMdg2oshuki': 'learn anything - programming - programming languages - elm',
  'dzhbs3FRB4z143969SjnPEDspe1Gp3SEppissAqy': 'learn anything - programming - version control - git',
  '9J1fJTLMtBohP398Zs1axCyQf7v4nFyoMTWuG9P5': 'learn anything - game development - game engines - godot',
  'qpLq1TfqPWmu9sszrCxEM4QsWUH547TLNQkyfTyQ': 'learn anything - programming - programming languages - go',
  'dXTCUUkXaSp99j3nbD2Gzxn5NMBn8dyuU4atT51n': 'learn anything - mathematics - graph theory',
  '3LqqYjEYQWQsrSk3Ypvy193fTspqZuiCy4emM7Bz': 'learn anything - design - graphic design',
  'CBJmkdWELRW4PYpUDj5ypLeydiAn1io41CrpHpF2': 'learn anything - mathematics - group theory',
  '2t2hzaNKKxQ5L6zaAEgpguLbJYL24gX8hi8hgrFM': 'learn anything - programming - programming languages - haskell',
  '9XKbbxW8Ft3fzP43bPwtqU3PRhDzp3VjKsqLntQJ': 'learn anything - web development - front end - html',
  '4LknBLWzBESbxERfpYQZsa2Fv1k3Lne1FjVsD4ys': 'learn anything - health',
  't1dtQBegP9uwBMKgxszHeHhYRT8EzDvbxy9Zbstw': 'learn anything - computer networking - protocols - http',
  'poAjesfjxdw5oHhJJT1LbPi4pabM6gBh1kKzrS3E': 'learn anything - art - generative art',
  'zRGj6Bjd1T31sVhsJz4HcNbCCz7ZMgKNqJSWSjyt': 'learn anything - web development - front end',
  'YsbzN9qSqh19C8xSu48PVMsDYik1obzQLb4qUNTN': 'learn anything - biology - genetics',
  'viRDhbpcrjLW2MSyzGJyhzgSqryics23wcLfJTxR': 'learn anything - history',
  'sCYVzti3VNqepg8uKQxpGQoHnDFy3pyuBiabecPn': 'learn anything - mathematics - geometry',
  'FALM4KzKneJrqTQpd9fc8ZQyneE228tWpAVcB5f1': 'learn anything - programming - programming languages - idris',
  'sG3PrxZ5rtpFSBEWewrbfGkSiaXduHMZxEWRRewi': 'learn anything - design - industrial design',
  'VBPfyy3FxxfSpCB6xzjQUxbKbmvPf6w9W7snssVb': 'learn anything - infrastructure',
  'paZEegpBdjystmyVhqfqX7PoPquz1AEWY4JvQkSk': 'learn anything - computer networking - internet of things',
  'Hsex87wcsZbzbwMNzbaJFsBPFJycLymJqA7sotvg': 'learn anything - computer networking - protocols - ipfs',
  'GLyTce5yc3y6fxsHJqZSoP3UnR5pSx2My8cudp7o': 'learn anything - economics - investing',
  'm32Zo1SzPiqfWqJvpUwBMuTMCNVXejfyWfZyeSFz': 'learn anything - operating systems - ios',
  'Gr8yvuKJCWgjaeJXoiUudYqoid8oeky6b81Cwunf': 'learn anything - web development - javascript libraries - jquery',
  'XcFAZAvk82ipqdis1UW5wznzxBxuVbx5iHLwgLHP': 'learn anything - programming - programming languages - java',
  'o5MkZSpM5SvDhrBTz7mvrm7qLFSFXXAgV5xzKWQx': 'learn anything - programming - programming languages - julia',
  'rApczcRbzmMrgkZtP6QmEyTRGUvgiyThASZrPP5C': 'learn anything - machine learning - machine learning libraries - keras',
  'P1fXveGBaQQQF9u1ZjGzqJzT9vnUppxPgyrnYFzM': 'learn anything - mathematics - lambda calculus',
  '5PazdXmKxEq1mDpksAfWUZFdJTpvAHpti6Cir1S2': 'learn anything - web development - javascript libraries',
  'xGXnpQKEqRv7eHeqTwgz8CsdknxhnWZj68baiyCd': 'learn anything - law',
  'xmrq1nh3m3aseeRxiK7hexvqqKktdaLRSTGSq2pA': 'learn anything - psychology - cognition - learning',
  '4bwpnfgzEsxWdzsbgDzUJdK8qxmvEKEK8tdWPmD5': 'learn anything - design - typesetting - latex',
  'RzvJjKnkfVYcSZxfU8vozrx94yqAemYs6s5SRnoz': 'learn anything - linguistics',
  'QQzCynmUtZpAuyGipqxsvRJ6NPn477o9cSjCGqqR': 'learn anything - programming - programming languages - javascript',
  '9GQnwWMBYXMe1XjUD8G21qpxiyz5B4MraPtL8xyy': 'learn anything - mathematics - linear algebra',
  'U8N8tR2D1Ek1SUaLoNEDwcmoeeBRMkEUnd1XxfH6': 'learn anything - programming - programming languages - lisp',
  '1GGWUw7yg9oqPVsqx83FwnMa41ecAcYXYJp5GRRR': 'learn anything - mathematics - logic',
  'HpUzZFCiRpvNq4ahQ7kZzzMHtP5Mpsxw9aysneyX': 'learn anything - operating systems - linux - distributions',
  'jm89qy7HU6d8WuxRKdxrAicNnEgSPaeSJ7poN6VC': 'learn anything - operating systems - linux',
  'gKQdRD1VLLAi1etGdsKnhtXsW4WX8y6HQUQBx6eN': 'learn anything - game development - game engines - love',
  'PVcz8iqUfa941KTpBqXgpiP7Asst1yGcqVa8Kmit': 'learn anything - machine learning - machine learning libraries',
  '7yruRs7n4ySrpYqFppAaRJrdcf8MKpAfpyjnqV1z': 'learn anything - economics - macroeconomics',
  'YstbvV9fn1zzpkXxCsSAnzheSysDKn5Q3B8koMuf': 'learn anything - management',
  'Q8Rh6YMpzZrg6z2axSfSeU6vUxgNrbDaosMzuAAn': 'learn anything - operating systems - macos',
  'Wm2fSqKWEJyyZ3LYZsgy2x6Yb8te49t968qqypUs': 'learn anything - marketing',
  '5Sx8gmcsXTxznCp11pAggrxCzWkA4VLLNFx2RNEH': 'learn anything - programming - programming languages - matlab',
  'zv6SgpSpxyG8ZzXs7TpqV3Lzzms5yqa3pzC9CTnn': 'learn anything - medicine - specialties',
  'CbZkPeEWbQxNRtoCAzdy3Wx1Bz3BLzC3PsK9yF5q': 'learn anything - medicine',
  '5LipbLiRfryhTsqRL6za1x5qzpQBh3mmD997Kwvb': 'learn anything - programming - programming languages - kotlin',
  'stsEoNGkUKFSyU9tsZ79xwDwQqQWSufCXafvSdPx': 'learn anything - linguistics - languages',
  '4vwsEGr7GgX2F6iTU1gzu4wCByWxGi9HCTqW7ABp': 'learn anything - economics - microeconomics ',
  'k954FWFNztnkphWmNqqHz2dqQW41LeP1SLqkqqjs': 'learn anything - machine learning',
  'X1xhDwGWzsx5JAYpitKYQmX9YtMgR3CBpujMkhj8': 'learn anything - health - mindfulness',
  's7pJzgtWzzkz8ubfSzWxWyvuReC7eLVSHZqc4aRV': 'learn anything - art - music',
  'nFFywmhppMRxw1Z6n7QNxikisQo9q9egH5jL8PfD': 'learn anything - natural language processing',
  'h8VJGBSS26e4bB4WdUx3myyoUczihJtvzGGj8whg': 'learn anything - programming - programming languages - nim',
  'mLEApxUMnfyeMpB7WzzkUdUNAweVk9WWJZpXgsh6': 'learn anything - databases - nosql databases',
  '6fjPX63yK7dpB6Vs2uxjzqvZ8xBw2ymoDuq48wPC': 'learn anything - computer networking - protocols',
  'HbfUFjzkF9Dc1GnzXqs2rUpVy9dEsWBL61wKvsx7': 'learn anything - physics - nuclear physics',
  '66sFsUMNvxTztuXk4hHSKRByUXqnASaLTXMNrNkv': 'learn anything - web development - backend - nodejs',
  'VsJNqTHszge5FaDgKQXk94U6mzvFT5dSHd5cRu1p': 'learn anything - enviromental science - nuclear power',
  'XtFzGZzt2WmZXRs6R2yecX5yqPXn2rGvdTXhbtJ9': 'learn anything - mathematics - number theory',
  'zUyb7rGF3UvomE9YgA4tJ8vhfrGxZ9dvPNy2EL1r': 'learn anything - health - nutrition',
  'JD2DJUeZSAwQzyb5KceAZ6bfuYaLGqsDkpfZg1R2': 'learn anything - mathematics',
  'zpRZZGyaquCMMatMhbHqoyNDum3Nh6VTgyRwyDuY': 'learn anything - programming - programming languages - objective c',
  'zPHWFpAprmq1Tt3YGm3ZBE1pysmVUYSgDhsfMVfZ': 'learn anything - computer graphics - opengl',
  'dhjpxEvxsiojxW3zpYLauuaPtunmybtWNfUjmy4b': 'learn anything - chemistry - organic chemistry',
  '4ihKdHT7ZKc1a6hp7MiFFYGpzA4Dm6Qu6sr5LdMT': 'learn anything - security - penetration testing',
  '4XCVExihWLgHvFxnJZyxLMYWWt8rfsgi4Hrqykya': 'learn anything - programming - programming languages - perl',
  'qn6XqfNxftWrVm4n2Xs5BsPJok4KEFTJGpNixELq': 'learn anything - neuroscience',
  'DaLRfu3ipMHEkhxuzqKTgbZPLmVGTmN7khBS3xqZ': 'learn anything - philosophy',
  'ARzVgj42iJRgaDwqcHqpy6bVBskmZxbbzGsUyaYn': 'learn anything - art - photography',
  'KAxvkPhxHhf6v2xxJ58HXhduppxpTz8xznmcuvBZ': 'learn anything - operating systems',
  'UMM4zxspXCaoU2PXsuxQdj8ERppHZEpkv9oQAiuB': 'learn anything - philosophy - philosophy of mind',
  'zR23tD5fCFaQox7mHfYkLUgiQCDvMcz8Ragd98QR': 'learn anything - programming - programming languages - processing',
  'y48JgLrYtbyNrsKyRze4WHzhYVrGZks9N9pvsekp': 'learn anything - databases - relational databases',
  'DGpMF54UqFrrurzbs77HTzyq8HswHBEwq8xdg8hB': 'learn anything - programming - programming language design',
  'RfCpjqozA6Aq3j38RvzUnZrhFGMnpCsbRrpAsUWj': 'learn anything - physics',
  'XSoat9hfA9vpEu9LsEStbuAzNWhPHZqDyh24sRzv': 'learn anything - programming - programming interview preparation',
  'RHEKsTCqdDLjzVaZ8DzEXkeEezxpmyLsqf5BV1Mt': 'learn anything - programming - programming mastery',
  '6GZfjhTKw6cscXsr3MqFCLAfPnCs9dEEWSAuptrR': 'learn anything - computer science - programming language theory',
  'FfGBsH3yoyhMqibLaNW8hf3ZKGe59Yx7yiNDBxc3': 'learn anything - art - public speaking',
  'XK73eU8WNHy5qHEnsKTKqSdsVkXzs2iMtvTmgYpc': 'learn anything - programming',
  'deC8Q7qpC5GxM41ysqHhMHzN832JMUAL1Fc351Td': 'learn anything - programming - programming languages',
  'VznvpXy4JfeyVL4toshCQE3pdyHvLzx1bTGUpze2': 'learn anything - machine learning - neural networks',
  'cmk4fh551FmyBm5Eg3vAbj9zruxk3W41XNreG4vy': 'learn anything - psychology',
  '9ABQqxkZGqGtY2QKRkwyt7q3pfzMkoSQTgJ5anZn': 'learn anything - machine learning - machine learning libraries - pytorch',
  'F8ubCrxApr7pFiW8TxvNyyzD51WqHkzVDFMN4cyp': 'learn anything - physics - quantum mechanics - quantum computing',
  'uFiw9mUYxyQjTnTcHqpX8VGsH5sSVSWztpY5AyWJ': 'learn anything - security - privacy',
  'mUPs3DfcabhJX4AWRPWVdbYRkqqad3ZL2SjVFoPL': 'learn anything - programming - programming languages - r',
  'ZLb6tystjm7WXtPgscpXpxKiDktvqcqvvUbptrER': 'learn anything - psychology - cognition - rationality',
  'cmzq9sEGAyyNyeZrNA7UyQa8JpsqHf9QzStwFqGT': 'learn anything - programming - programming languages - python',
  'b67moawHdg45kYPyzUUUt3doLV1jzgD12FYAayxJ': 'learn anything - computer graphics - ray tracing',
  'qJ23VQZs8r5YToae7Ch6Tein6h7U5yhAiw8enxsH': 'learn anything - physics - quantum mechanics',
  'WoxCvQtJKD7iFsABg3sRjfAfQ2g5ZQjmTt6Vd25i': 'learn anything - programming - programming paradigms',
  'Fb7dmtCvahWRF1LWybq5JqtPjHwBeF4mxoV7zLB5': 'learn anything - databases - nosql databases - redis',
  'MiLsnxiprq4jpBMTBiHT48Kt1sZqfF23hEuyGLKE': 'learn anything - web development - javascript libraries - react native',
  'reBzaM1mn6WWuTM5iRAtrC1o7LzWBNwspT9pxNT3': 'learn anything - computer science - regular expressions',
  'eKswyDv4KNY9fePuF3DcWvYZjtTaBzxk581Mw7Ru': 'learn anything - machine learning - reinforcement learning',
  'dtFqPNRpHxvWsy1ySv4oA48sDxPa87SpfFq5Zzqz': 'learn anything - programming - reverse engineering',
  'ifaZsjVmDsFxTdqDDix8s3GyXibGvCArpc86ViZM': 'learn anything - web development - javascript libraries - react',
  'G4qPtRmbTgp4RCq6S4zSDmbEfBkzw3bi69DZqNqE': 'learn anything - computer hardware - robotics',
  '4eQcjH3g5sypLz42tryUQ49NZzfhE3Crb4m9tq1v': 'learn anything - linguistics - languages - russian',
  'y48JgLrYtbyNrsKyRze4WHzhYVrGZks9N9pvsekp': 'learn anything - databases - relational databases',
  '7Q14XaYLnco9X1oqfouxpibjMz3Asy6PVDjf8C3Y': 'learn anything - programming - programming languages - rust',
  'z5jpzSuE3Tdyy4TFpxz3vbZMAKyS6B4cDPNQKmS2': 'learn anything - programming - programming languages - scala',
  '7YbqKxSpWxkBT4s4p8N5HghpCy6n8XNHwSHAppzn': 'learn anything - web development - search engines',
  'tjqqGCFLZbqp4sEDZqv7H6DB5Xwx7FUjhDdpBnit': 'learn anything - programming - programming languages - ruby',
  'BTNhqptfyxynrT4NFoaLAysgHnkKgpC98YGuKqRA': 'learn anything - natural language processing - sentiment analysis',
  'LzEyZ1zXzYtx17vmqsn1ddeVAzRNPZscLvdgNkmc': 'learn anything - art - singing',
  'nczskizQHzyMnnpAxxg5D2hWuMshy2AF13pkGNdk': 'learn anything - mathematics - set theory',
  'rv35EzC72HtQBmAse2k9WgxyssY4qTbs2u3FU9ux': 'learn anything - programming - programming languages - smalltalk',
  'syqmsqY4ZxxGLHMJFc1s84WXdU4eC3MxdZPa9eSd': 'learn anything - sociology',
  'eGwQJjrztCQoaUZwUdAeq2o4C1s9mdHKRKjX6iRD': 'learn anything - programming - software development - software architecture',
  '38DGvay2sqnzEMAZ4GnPNKzVxDic1gStaQq6dn46': 'learn anything - security',
  '7zQmJgzwiJusj356NbqrERGDJkX3bRSLJH65tp35': 'learn anything - computer networking - software defined networking',
  'gLpu3axPp2y3uXJoq4G5F2bCzbLNDn9Vi1rnaZLH': 'learn anything - physics - special relativity',
  '4TdQ9XwhpRja4c9Nz7XvCSL1k3UsHFs8U2fxjfwd': 'learn anything - computer networking - protocols - ssh',
  '6tM7DsVd3ByH4rCXFw6XyH59y4xEzEsSzNtasAXN': 'learn anything - tooling - text editors - sublime text',
  'zZbLxuhSrDnUaU3aP21wpUwt62zmVpkct13QhJjU': 'learn anything - computer networking - protocols - tcp-ip',
  'ha4YuYgp6HcpogCup28Nx4v8YbJdepvRB7ys8wv8': 'learn anything - tooling - text editors',
  '48Lde9zsysCqsBfqQAMmqrgApPsxhxebtxPqe173': 'learn anything - tooling',
  'vAJcWyzzTubpywgp8o367gPWvRUxi2y5r2sZMryb': 'learn anything - programming - programming languages - swift',
  'zqcBKdtGqSVwEik7gqrYrynGeyfSXYLVyqxE72Q2': 'learn anything - machine learning - machine learning libraries - torch',
  'eytyqpDLBmrC4xVnHCDqRVBZi39xhXBWnBRSTVoM': 'learn anything - mathematics - type theory',
  'qA5158JZkdJzGWzr54AswZkmxPnwBJVTc89mytzy': 'learn anything - machine learning - machine learning libraries - tensorflow',
  '7cSLjj5rauAnjWT1zHqEmqGkixvoVWaMz8C7Q2aW': 'learn anything - mathematics - statistics',
  'cpmV5tcQPug6EV6BspmqdGjEi11yPHxza4MkVjm4': 'learn anything - computer science - theory of computation',
  '5LipbLiRfryhTsqRL6za1x5qzpQBh3mmD997Kwvb': 'learn anything - programming - programming languages - kotlin',
  'Dpe6usjyhYStxvMwwrGB2oste4DsnbGdQxL8h1eU': 'learn anything - design - typography',
  'e6eGCsYMysgfLWp32sC94KKjriUy5UNmBJXJGoox': 'learn anything - game development - game engines - unity',
  'vYosAZHZypgizmPLqEDEhcvoGNTAUPHz7eBVyf9R': 'learn anything - operating systems - shells',
  'HxHcbJzNjqT4s8esfDyUQYEACFDysxTx43FUGdYx': 'learn anything - design - user experience',
  'zrL3XX4z7bcSDuQrLwXNAqdZr6VCp8JbMXvksso2': 'learn anything - tooling - text editors - vs code',
  'nGBJtTf4DYUj4sxXXZRBn7YkRnxb1LtqLmzhonLn': 'learn anything - web development - javascript libraries  - vuejs',
  'tfSGpEVZd5EqPFzEzetA532qCfhgUDfbVp6gU7zv': 'learn anything - web development - web crawlers',
  '3irQvGhTDXsWX7yHqzQkR9JWhq9kyaJZ4otN7qiR': 'learn anything - web development - web design',
  'HxHcbJzNjqT4s8esfDyUQYEACFDysxTx43FUGdYx': 'learn anything - design - user experience',
  'mKhEXHiMUXpGgfJxDkqbgyxN3MRp3bwug96a9zo2': 'learn anything - virtual reality',
  'CxJxqiNzZTkFiUUsa3ML2Hm3Zo4Y94nLeH745BUR': 'learn anything - text editors - vim',
  'TTiDHqPUigF91yBHAFSgbhNckeUAGZhNtxiavEPB': 'learn anything - web development - web performance',
  's6pamFzVLsjqEmECkedvcFuH8pdM47NuojDs8epy': 'learn anything - web development - javascript libraries - webpack',
  'Z23exvKV95hC8L5i5kcyenuTr1XykRqXWweZAqfi': 'learn anything - computer networking - protocols - webrtc',
  '85uh2iN4GPhBJpuyyuWks5a6niyypQA5TPBCGnAN': 'learn anything - web development',
  'MCHX7afgsj6V5qXGDEpoqs4uJhG9yDPsTaz4WyP4': 'learn anything - computer networking - protocols - websocket',
  'syW5tDqyLdEPRQYt2d8bhbt79hqPxreaaKo3BqMG': 'learn anything - art - writing',
  'yxcnFoyVpJecxFRoqfQ8orzsu3zesCAcS9jjMPZM': 'learn anything - operating systems - windows',
  'gDAemvFSLEMi7g9ozVTKp7yW2onyv76X5cspxeVQ': 'learn anything - physics - quantum mechanics - quantum field theory',
  'xPUGxGodprtehL3P5zd7dyzmTeaDYiCQxkVp8nrF': 'learn anything - art - music - guitar',
  'M66CXTQkXDysSKDp3a3Mq3Dbwzy5x398Ayvzc1Ey': 'learn anything - mathematics - model theory',
  '9Vyqzw7KposgvsspFnRr96nFCyNcKKUVG4hpuNYw': 'learn anything - mathematics - topology',
  'Gq7pA3rtpYhZP2K1MhMFwmy3YaEpvdG13M5wjRBi': 'learn anything - mathematics - knot theory',
  'HbPdBs4yqvN1FdoScE3PVNZwnXcqdddWqXkGqssc': 'learn anything - web development - javascript libraries - meteor',
  '35hVLCpp3wbpsx4YqVD9XxpczbpPpyWJjwWfsfAq': 'learn anything - machine learning - machine learning libraries - scikit-learn',
  'eD7tx71JUqC6R4iqaPGxzvdR2ocpqGq5TVsxp2yk': 'learn anything - web development - javascript libraries - redux',
  'pT3imu8pRh4xtPpe45UYAEGz7ehkMqWna1sPgWbL': 'learn anything - linguistics - languages - german',
  'K5WJhHspfaaezNNbNRZYxWGEoofFqnQVTa3ZcxEz': 'learn anything - web development - full stack - django',
  'PRPMKGkoCxUbGwDxRxfWCPspQppWEL4wcrf3LteY': 'learn anything - programming - programming languages - php',
  'amC8qjhodpnZHjXHDxxyeSpKSMU65DUb1yyirRMk': 'learn anything - linguistics - languages - chinese',
  '26VQE2ahqWLR5jRQCdsChym1EUP2Ls8AmQ64aj2y': 'learn anything - programming - query languages',
  'QBvN8M3BBDqL2TKXpGzyycUxTMYcRzXpQoJKDcdq': 'learn anything - programming - query languages - graphql',
  'Bq15VPP9eVsmunFsM9RAFjpawSsgpuCBSi9ou3ye': 'learn anything - design - graphic design - photoshop',
  'mckfV3fnWaJJirpCTcieUhRdyMT3TuLHq6RY54Gs': 'learn anything - programming - software development - devops - docker',
  'TCxkEPQuB1ApGPDJT4RcsusD7JFkgNq4HjwAqbLj': 'learn anything - programming - software development - devops - aws',
  'qD6Dva6VnUKLM1xg3tisnTznnXkBgpYd8nfyjGkn': 'learn anything - programming - software development - devops - kubernetes',
  '6WmDpnHqF93PcBqtajq5Y2kFTy3HqyadWjazqqAU': 'learn anything - programming - programming languages - c#',
  'Cqy6H5RRvkwBTFEsTFH1eW8zQFA5Gzvoq6ssjFxc': 'learn anything - databases - blockchain',
  'odBHYpJQbM7LnyCw69K3KHCrKBBzeAUUQXktaKdf': 'learn anything - data science - apache spark',
  'F7y3iSAwZdzGnRRWLur3RpXiJviy1YF7QxZwDLxv': 'learn anything - linguistics - languages - japanese',
  'kAMXBibSaps4PdfxkB4jBoYBxWBfMbk1eYEzo6Cz': 'learn anything - databases - graph databases',
  'C6qyyeVEzfVCyvpxD7digZzzGxV8hvcwdzAkkpjF': 'learn anything - programming - software development',
  'oABafsSirqHz4o8Nh4pLqwCjbqnkFE4YturNm3CS': 'learn anything - web development - javascript libraries - d3js',
  'yyJxSXTCh9xqmnCSbfoD5Ms7Nry1jxcymUDfMNqB': 'learn anything - programming - design patterns',
  'MbpPqGzHzySQesda9G5umY28S3spWRbzgCrGb4Uv': 'learn anything - web development - backend - laravel',
  'zxRG1oYfCw5DU8ExnRnyJt6qAWz9MM41sqhniGyv': 'learn anything - data science',
  'KRHuHfpmq5DzmpfFEgyvSyzQtk9t6oy7faNKbtiL': 'learn anything - computer hardware - arduino',
  'pB9HWsxJd9fybGJtXLbiXnrMdzPhtF47yKTq3QMF': 'learn anything - computer hardware - computer',
  '88ngrfYXYvJvtjsrUk6yEB1wwkKHexABji2z6sjn': 'learn anything - machine learning - neural networks - convolutional neural networks',
  'gkqG8tMFYa6K3qpgvqpgnz85TsJ3UpwCuiQpQPjK': 'learn anything - web development - front end - bootstrap',
  'TWYxfqzhfcp2sZJUGpHnZqz4fY8YFAjiuv6JBhDQ': 'learn anything - computer hardware - raspberry pi',
  'xb6QwzqtZ2sZ2ryvTeXhA8PnUdzFTWZocEoCxeZp': 'learn anything - linguistics - languages - spanish',
  'pRs2UppBdxxyS7YxD3KuqyMsFz5BNsNAyyAzzTfq': 'learn anything - computer graphics - webgl',
  'Tdvsb72Fqon42xkZGHsQx1xfKk6F6eGsgPAjCFpq': 'learn anything - art - dancing',
  '44Pdg9ZnUsddwk5iWYwH2q2a5xHspBesoDQ2HY31': 'learn anything - linguistics - languages - french',
  '4pT3AeEEywqSgdxTFBRgq3bmFpLs6s9YSaNMrxZY': 'learn anything - programming - software development - devops',
  'ELcJKvcycS3o6xNu8a6pgF88wCyq5wUkZRWvsfnu': 'learn anything - programming - software development - software testing',
  'QYBozsiUWZjbqguqyKSUV3psfhganW7PB1Wapxax': 'learn anything - web development - javascript libraries - angularjs',
  'hGPfuwm3pbzHXVVmB3kGRJKcPGPgeZAVFQGztxHW': 'learn anything - programming - programming languages - assembly - WebAssembly',
  'i2KJsa46DzxEMaziscL7xMzJMxqAtnNFNAXaJ6d1': 'learn anything - programming - software development - open source',
  '3WHuPMbUhikHhUQyKxZZ1yapNe4yp9jQcz4u55my': 'learn anything - data science - information retrieval',
  'p6P2zXxZjuHy2pwzzy6yi14hPD8Nd4BQj6vraSAi': 'learn anything - programming - programming languages - c# - dotnet',
  'qxB5SQXpxFML8WSYfgpgs9c1zvyyu1JXGbGzSZGf': 'learn anything - programming - software development - devops - ansible',
  '8MxSwVTHS8KP3pptyt26TxDj2urxLsTxoaquJGiE': 'learn anything - web development - javascript libraries - babel',
  'xoSN9tB2yvSa2q9kboV32BC789FasA1HNxMfy536': 'learn anything - games',
  'PbBNcxWhy1BNfFyCcDGutjyYwBBquHpTsDPDasTq': 'learn anything - board games - chess',
  'AAT9ANXEqcbXVcypJUmtpuAEVFSxpWPsDgpRDqts': 'learn anything - board games - go',
  'Cyv3UUXjxZst5FjBnpkSdqn7XtqWmiZsJL3Hqqec': 'learn anything - programming - programming languages - ruby - ruby on rails',
  'hKbd75qAYjBQtWMN4pzVcVnujGPppqWUKvFyYA2B': 'learn anything - programming - programming languages - assembly',
  'vgUdobqCgPAzpNFwxi779aqRiqcHTXcgmrskyQqd': 'learn anything - programming - software development - devops - nginx',
  'KdeMPbxs8KPixsa5YUq5cphqJnQg81vpHaXcDX2i': 'learn anything'
};
